### ISSUE TITLE
racer crashes on standard library completion

### ISSUE THREAD

**Issue by btoninho** [racer-rust/racer#1002]
Apologies in advance if this is something I did fundamentally wrong.

The following code:

    fn main() {
        let s = "Foo".as_bytes(); 
        let t: std::slice::Iter = s.
    }

Fails to produce any autocompletion for the `s.` part. Completion for string "Foo" and the std::slice:Iter parts work correctly. 
RUST_SRC_PATH is set to ~/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src as intended.
I am using the latest build of racer on MacOS and racer produces the following backtrace:

> thread 'searcher' panicked at 'load file successfully: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
>    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
>    1: std::sys_common::backtrace::_print
>    2: std::panicking::default_hook::{{closure}}
>    3: std::panicking::default_hook
>    4: std::panicking::rust_panic_with_hook
>    5: std::panicking::continue_panic_fmt
>    6: rust_begin_unwind
>    7: core::panicking::panic_fmt
>    8: core::result::unwrap_failed
>    9: racer::core::FileCache::load_file
>   10: <racer::core::Session<'c> as racer::core::SessionExt>::load_source_file
>   11: racer::nameres::search_for_impls
>   12: racer::nameres::search_for_impl_methods
>   13: <racer::ast::ExprTypeVisitor<'c, 's> as syntax::visit::Visitor<'ast>>::visit_expr
>   14: <racer::ast::LetTypeVisitor<'c, 's> as syntax::visit::Visitor<'ast>>::visit_local
>   15: <scoped_tls::ScopedKey<T>>::set
>   16: syntax::with_globals
>   17: racer::typeinf::get_type_of_match
>   18: <racer::ast::ExprTypeVisitor<'c, 's> as syntax::visit::Visitor<'ast>>::visit_expr
>   19: <scoped_tls::ScopedKey<T>>::set
>   20: syntax::with_globals
>   21: racer::ast::get_type_of
>   22: racer::core::complete_from_file_
>   23: racer::run_the_complete_fn
> ERROR 2018-11-21T17:51:33.469582000Z: racer: Search thread paniced: Any
> END

Is it something on my end?

**Comment by tseco** [comment]
Hello, I'm facing the same issue - I get the same 

> thread 'searcher' panicked at 'load file successfully: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5

error.
Following are a couple more examples where auto-complete fails, in case further illustration is necessary:
```
fn f0(s: &str) {
    for l in s.lines {
        // does not auto complete:
        if l.
    }
}

fn f1(s: &String) {
    for l in s.lines() {
        // auto completes
        if l.c
    }
}

fn main() {
    let s = String::from("");
    for l in s.lines() {
        //auto completes:
        if l.c
    }
}
```

**Comment by kngwyu** [comment]
@btoninho 
Really thanks for opening this issue!
More precise debug info:
```
thread 'searcher' panicked at 'Failed load file "": Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5
```
It looks racer searches a file named "" :thinking:
