### ISSUE TITLE
100% CPU when completing certain nested use statements

### ISSUE THREAD

**Issue by Palladinium** [racer-rust/racer#1009]
I've attached a minimal example, racer 2.1.13 running `racer complete 1 25 <file>` prints the line `PREFIX 25,25,` and then spins indefinitely, while I'd expect either an empty completion list or some sort of error message.

The issue seems to be appearing only with nested imports, for both `crate` imports and dependency crate imports, but curiously I haven't been able to reproduce it with the standard library.

[racerwO0fgd.zip](https://github.com/racer-rust/racer/files/2688223/racerwO0fgd.zip)

**Comment by Palladinium** [comment]
Example for a library `use` which exhibits the same behavior on `racer complete 1 27 <file>`, as well as one of a standard library statement that doesn't exhibit it.

[racer_lib_example.zip](https://github.com/racer-rust/racer/files/2688235/racer_lib_example.zip)
[racer_std_example.zip](https://github.com/racer-rust/racer/files/2688236/racer_std_example.zip)

**Comment by kngwyu** [comment]
Thanks, @Palladinium! 
I fixed it by https://github.com/racer-rust/racer/commit/f462768a72fe4c1917a675ab2f6f36ce8527bb2d
