### ISSUE TITLE
Installation fails with smallvec compilation failure

### ISSUE THREAD

**Issue by nic-hartley** [racer-rust/racer#1023]
I just now tried `cargo install racer` and got this error:

```
Compiling smallvec v0.6.9
# errors
error: Could not compile `smallvec`.
```

I've raised [an issue on smallvec](https://github.com/servo/rust-smallvec/issues/141) about the actual compile failure -- this issue is strictly about working around it for the time being, while smallvec fixes the underlying cause. Maybe pinning the imported version to 0.6.8, if that suffices and works?

**Comment by kngwyu** [comment]
Please try `cargo +nightly install racer`

**Comment by nic-hartley** [comment]
Install succeeds on nightly @kngwyu. I feel like requiring nightly is a workaround at best, though...

**Comment by kngwyu** [comment]
It's because of rustc-ap-syntax needs nightly and I don't have enough time to migrate to stable parser, like syn.
