### ISSUE TITLE
2.1.19 and 2.1.18 tags are missing on GitHub unlike crates.io

### ISSUE THREAD

**Issue by jbeich** [racer-rust/racer#1024]
Downstream may use GitHub as the source of truth. Were those actually released?
[![Packaging status](https://repology.org/badge/vertical-allrepos/rust:racer.svg)](https://repology.org/project/rust:racer/versions)

**Comment by kngwyu** [comment]
Thanks, I just forgot to push a tag to github.

**Comment by jbeich** [comment]
Push v2.1.18, too. For posterity.

**Comment by jbeich** [comment]
v2.1.18 tag is still missing, so there's a gap between v2.1.17 and v2.1.19. It's not clear which commit 2.1.18 release on crates.io corresponds to.

**Comment by kngwyu** [comment]
Just pushed it now, thanks.
Looks I mistakenly pushed it to my origin... :roll_eyes:
