### ISSUE TITLE
racer doesn't complete use crate_name::{

### ISSUE THREAD

**Issue by GopherJ** [racer-rust/racer#1043]
racer --version
```
racer 2.1.22
```

rustup --version
```
rustup 1.17.0 (069c88ed6 2019-03-05)
```
This is what I get when I type:
```
use futures::
```
![Screenshot from 2019-05-25 19-02-24](https://user-images.githubusercontent.com/33961674/58368438-c22db580-7f1f-11e9-883e-b8546fad314a.png)

This is what I get when I type:
```
use futures::{
```

![Screenshot from 2019-05-25 19-02-39](https://user-images.githubusercontent.com/33961674/58368443-d4a7ef00-7f1f-11e9-9df2-4d162c0141c2.png)

**Comment by kngwyu** [comment]
Hmm interesting.

**Comment by GopherJ** [comment]
is there any news about this?

**Comment by rbartlensky** [comment]
This seems to be working for me just fine. I compiled racer from source (commit 218682d3b8c79ede8fa1551182f7cacb30d35368)

**Comment by kngwyu** [comment]
OK, thanks
