### ISSUE TITLE
Completion not working with Rust 2018 `no more mod.rs`

### ISSUE THREAD

**Issue by xabufr** [racer-rust/racer#1052]
Racer isn't able to complete modules that looks like `my_module.rs`, `my_module/sub_mod.rs` (https://doc.rust-lang.org/nightly/edition-guide/rust-2018/module-system/path-clarity.html#no-more-modrs).
Changing to `my_module/mod.rs`, `my_module/sub_mod.rs` makes it work again.

**Comment by kngwyu** [comment]
Oops, I didn't know that :thinking:

**Comment by malthe** [comment]
This seems to affect for example [futures_channel](https://docs.rs/futures-channel/0.3.1/futures_channel/) where Racer isn't able to find the "mpsc" and "oneshot" modules.
