### ISSUE TITLE
racer-find-definition async syntax support?

### ISSUE THREAD

**Issue by apiraino** [racer-rust/racer#1055]
I tried using racer on what I believe is a soon-to-be stable [async/await Rust code](https://github.com/rustasync/runtime/blob/master/examples/hello.rs):

![Screenshot from 2019-07-09 16-58-51](https://user-images.githubusercontent.com/6098822/60899508-e1339d00-a26a-11e9-8b9b-562f13b8ceca.png)

when the cursor is over `say_hi().await` I cannot jump to the function definition above:
```
$ racer find-definition 9 5 say_hi src/main.rs 
END
```

If I turn that snippet into sync code, it resolves the definition:
```
$ racer find-definition 9 5 say_hi src/main.rs 
MATCH say_hi,3,3,say_hi,Function,fn say_hi()
END
```

Opinions? Is my assumption correct?

**Comment by kngwyu** [comment]
Yeah, it's not supported yet because of my negligence :cold_sweat: 
Good catch, thanks.

**Comment by apiraino** [comment]
No worries! Just needed confirmation that it's not a bug but a ... feature :-)

FWIW: thanks for all your work on racer :1st_place_medal:

**Comment by johalun** [comment]
Hey! How are we looking on this? I jump a lot between async functions so this would really help :+1:
