### ISSUE TITLE
Racer doesn't autocomplete without `extern crate`

### ISSUE THREAD

**Issue by velvetops** [racer-rust/racer#1056]
I use racer in neovim but I can't get completion without writing `extern crate`. Is there any way to complete declaring this? 

Here my Rust environment
```console
cargo --version: cargo 1.36.0 (c4fcfb725 2019-05-15)
rustc --version: rustc 1.36.0 (a53f9df32 2019-07-03)
racer --version: racer 2.1.5
rustup --version: rustup 1.18.3 (435397f48 2019-05-22)
```

Success:
<img width="519" alt="Screen Shot 2019-07-10 at 14 36 21" src="https://user-images.githubusercontent.com/39664774/60943579-5b265d80-a321-11e9-9070-90cea53ebf0c.png" title="Success">

Failure:
<img width="516" alt="Screen Shot 2019-07-10 at 14 36 38" src="https://user-images.githubusercontent.com/39664774/60943590-64172f00-a321-11e9-9d78-a250d3a5ccb2.png" title="Failure">

**Comment by velvetops** [comment]
Sorry, my vim config was wrong

**Comment by kngwyu** [comment]
Looks your racer is too old(current version is 2.1.23)
