### ISSUE TITLE
cargo +nightly install racer Error

### ISSUE THREAD

**Issue by k4lm4rx** [racer-rust/racer#1069]
I am trying to install *racer*, but I keep getting this error.
I tried setting *nightly* as default, didn't work either.

# Info
<pre>$ rustup show
<b>Default host: </b>x86_64-unknown-linux-gnu

<b>installed toolchains</b>
<b>--------------------</b>

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

<b>active toolchain</b>
<b>----------------</b>

stable-x86_64-unknown-linux-gnu (default)
rustc 1.37.0 (eae3437df 2019-08-13)
</pre>

<pre>$ rustup update
<b>info: </b>syncing channel updates for &apos;stable-x86_64-unknown-linux-gnu&apos;
<b>info: </b>syncing channel updates for &apos;nightly-x86_64-unknown-linux-gnu&apos;
<b>info: </b>checking for self-updates

   <b>stable-x86_64-unknown-linux-gnu unchanged</b> - rustc 1.37.0 (eae3437df 2019-08-13)
  <b>nightly-x86_64-unknown-linux-gnu unchanged</b> - rustc 1.39.0-nightly (618768492 2019-09-05)
</pre>

# Fail
<pre>$ cargo +nightly install racer
<font color="#55FF55"><b>    Updating</b></font> crates.io index
<font color="#55FF55"><b>  Installing</b></font> racer v2.1.25
<font color="#55FF55"><b>   Compiling</b></font> autocfg v0.1.6
<font color="#55FF55"><b>   Compiling</b></font> libc v0.2.62
<font color="#55FF55"><b>   Compiling</b></font> semver-parser v0.7.0
<font color="#55FF55"><b>   Compiling</b></font> arrayvec v0.4.11
<font color="#55FF55"><b>   Compiling</b></font> rand_core v0.4.2
<font color="#55FF55"><b>   Compiling</b></font> nodrop v0.1.13
<font color="#55FF55"><b>   Compiling</b></font> cfg-if v0.1.9
<font color="#55FF55"><b>   Compiling</b></font> proc-macro2 v0.4.30
<font color="#55FF55"><b>   Compiling</b></font> scopeguard v0.3.3
<font color="#55FF55"><b>   Compiling</b></font> memoffset v0.2.1
<font color="#55FF55"><b>   Compiling</b></font> lazy_static v1.4.0
<font color="#55FF55"><b>   Compiling</b></font> stable_deref_trait v1.1.1
<font color="#55FF55"><b>   Compiling</b></font> rustc-rayon-core v0.2.0
<font color="#55FF55"><b>   Compiling</b></font> log v0.4.8
<font color="#55FF55"><b>   Compiling</b></font> proc-macro2 v1.0.2
<font color="#55FF55"><b>   Compiling</b></font> byteorder v1.3.2
<font color="#55FF55"><b>   Compiling</b></font> unicode-xid v0.1.0
<font color="#55FF55"><b>   Compiling</b></font> smallvec v0.6.10
<font color="#55FF55"><b>   Compiling</b></font> syn v0.15.44
<font color="#55FF55"><b>   Compiling</b></font> rustc-rayon v0.2.0
<font color="#55FF55"><b>   Compiling</b></font> unicode-xid v0.2.0
<font color="#55FF55"><b>   Compiling</b></font> either v1.5.2
<font color="#55FF55"><b>   Compiling</b></font> syn v1.0.5
<font color="#55FF55"><b>   Compiling</b></font> indexmap v1.1.0
<font color="#55FF55"><b>   Compiling</b></font> rustc-ap-graphviz v546.0.0
<font color="#55FF55"><b>   Compiling</b></font> memchr v2.2.1
<font color="#55FF55"><b>   Compiling</b></font> bitflags v1.1.0
<font color="#55FF55"><b>   Compiling</b></font> serde v1.0.99
<font color="#55FF55"><b>   Compiling</b></font> ryu v1.0.0
<font color="#55FF55"><b>   Compiling</b></font> rustc-ap-rustc_target v546.0.0
<font color="#55FF55"><b>   Compiling</b></font> scoped-tls v1.0.0
<font color="#55FF55"><b>   Compiling</b></font> unicode-width v0.1.6
<font color="#55FF55"><b>   Compiling</b></font> quick-error v1.2.2
<font color="#55FF55"><b>   Compiling</b></font> termcolor v1.0.5
<font color="#55FF55"><b>   Compiling</b></font> annotate-snippets v0.6.1
<font color="#55FF55"><b>   Compiling</b></font> itoa v0.4.4
<font color="#55FF55"><b>   Compiling</b></font> rustc-ap-syntax v546.0.0
<font color="#55FF55"><b>   Compiling</b></font> regex-syntax v0.6.12
<font color="#55FF55"><b>   Compiling</b></font> vec_map v0.8.1
<font color="#55FF55"><b>   Compiling</b></font> strsim v0.8.0
<font color="#55FF55"><b>   Compiling</b></font> rustc-ap-rustc_lexer v546.0.0
<font color="#FF5555"><b>error[E0433]</b></font><b>: failed to resolve: could not find `property` in `unicode`</b>
   <font color="#5555FF"><b>--&gt; </b></font>/home/marx/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_lexer-546.0.0/src/lib.rs:672:24
    <font color="#5555FF"><b>|</b></font>
<font color="#5555FF"><b>672</b></font> <font color="#5555FF"><b>| </b></font>        core::unicode::property::Pattern_White_Space(c)
    <font color="#5555FF"><b>| </b></font>                       <font color="#FF5555"><b>^^^^^^^^</b></font> <font color="#FF5555"><b>could not find `property` in `unicode`</b></font>

<font color="#FF5555"><b>error[E0599]</b></font><b>: no method named `is_xid_start` found for type `char` in the current scope</b>
   <font color="#5555FF"><b>--&gt; </b></font>/home/marx/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_lexer-546.0.0/src/lib.rs:689:33
    <font color="#5555FF"><b>|</b></font>
<font color="#5555FF"><b>689</b></font> <font color="#5555FF"><b>| </b></font>            || (c &gt; &apos;\x7f&apos; &amp;&amp; c.is_xid_start())
    <font color="#5555FF"><b>| </b></font>                                <font color="#FF5555"><b>^^^^^^^^^^^^</b></font>

<font color="#FF5555"><b>error[E0599]</b></font><b>: no method named `is_xid_continue` found for type `char` in the current scope</b>
   <font color="#5555FF"><b>--&gt; </b></font>/home/marx/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_lexer-546.0.0/src/lib.rs:708:33
    <font color="#5555FF"><b>|</b></font>
<font color="#5555FF"><b>708</b></font> <font color="#5555FF"><b>| </b></font>            || (c &gt; &apos;\x7f&apos; &amp;&amp; c.is_xid_continue())
    <font color="#5555FF"><b>| </b></font>                                <font color="#FF5555"><b>^^^^^^^^^^^^^^^</b></font>

<font color="#FF5555"><b>error</b></font><b>: aborting due to 3 previous errors</b>

<b>Some errors have detailed explanations: E0433, E0599.</b>
<b>For more information about an error, try `rustc --explain E0433`.</b>
<font color="#FF5555"><b>error</b></font><b>:</b> Could not compile `rustc-ap-rustc_lexer`.
<font color="#FFFF55"><b>warning</b></font><b>:</b> build failed, waiting for other jobs to finish...
<font color="#FF5555"><b>error</b></font><b>:</b> failed to compile `racer v2.1.25`, intermediate artifacts can be found at `/tmp/cargo-installsc6zOC`

Caused by:
  build failed
</pre>

**Comment by nylo-andry** [comment]
I am having exactly the same issue despite this issue being closed.

**Comment by kngwyu** [comment]
:thinking: 
@nylo-andry 
I cannot reproduce.
What's your compiler version?

**Comment by nylo-andry** [comment]
@kngwyu 

Here are my outputs:
# Info
```
$ rustup show                                                                                                                                              [2019-09-06 23:46:05]
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.37.0 (eae3437df 2019-08-13)

$ rustup update                                                                                                                                            [2019-09-06 23:48:44]
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: checking for self-updates

   stable-x86_64-apple-darwin unchanged - rustc 1.37.0 (eae3437df 2019-08-13)
  nightly-x86_64-apple-darwin unchanged - rustc 1.39.0-nightly (6e19f3f38 2019-09-06)
```

# Fail
```
$ cargo +nightly install racer                                                                                                                               
  Updating crates.io index
  Installing racer v2.1.25
   Compiling autocfg v0.1.6
   Compiling arrayvec v0.4.11
   Compiling libc v0.2.62
   Compiling semver-parser v0.7.0
   Compiling rand_core v0.4.2
   Compiling nodrop v0.1.13
   Compiling cfg-if v0.1.9
   Compiling scopeguard v0.3.3
   Compiling memoffset v0.2.1
   Compiling proc-macro2 v0.4.30
   Compiling lazy_static v1.4.0
   Compiling unicode-xid v0.1.0
   Compiling proc-macro2 v1.0.3
   Compiling byteorder v1.3.2
   Compiling stable_deref_trait v1.1.1
   Compiling log v0.4.8
   Compiling rustc-rayon-core v0.2.0
   Compiling smallvec v0.6.10
   Compiling unicode-xid v0.2.0
   Compiling syn v0.15.44
   Compiling rustc-rayon v0.2.0
   Compiling either v1.5.2
   Compiling syn v1.0.5
   Compiling indexmap v1.1.0
   Compiling memchr v2.2.1
   Compiling rustc-ap-graphviz v546.0.0
   Compiling bitflags v1.1.0
   Compiling serde v1.0.99
   Compiling ryu v1.0.0
   Compiling rustc-ap-rustc_target v546.0.0
   Compiling unicode-width v0.1.6
   Compiling scoped-tls v1.0.0
   Compiling quick-error v1.2.2
   Compiling itoa v0.4.4
   Compiling annotate-snippets v0.6.1
   Compiling rustc-ap-syntax v546.0.0
   Compiling termcolor v1.0.5
   Compiling regex-syntax v0.6.12
   Compiling rustc-ap-rustc_lexer v546.0.0
error[E0433]: failed to resolve: could not find `property` in `unicode`
   --> /Users/fanilo/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_lexer-546.0.0/src/lib.rs:672:24
    |
672 |         core::unicode::property::Pattern_White_Space(c)
    |                        ^^^^^^^^ could not find `property` in `unicode`

error[E0599]: no method named `is_xid_start` found for type `char` in the current scope
   --> /Users/fanilo/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_lexer-546.0.0/src/lib.rs:689:33
    |
689 |             || (c > '\x7f' && c.is_xid_start())
    |                                 ^^^^^^^^^^^^

error[E0599]: no method named `is_xid_continue` found for type `char` in the current scope
   --> /Users/fanilo/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_lexer-546.0.0/src/lib.rs:708:33
    |
708 |             || (c > '\x7f' && c.is_xid_continue())
    |                                 ^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: Could not compile `rustc-ap-rustc_lexer`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `racer v2.1.25`, intermediate artifacts can be found at `/var/folders/y9/kn5ybk3s1c3_65bhm833r5fc0000gp/T/cargo-install9fyILG`

Caused by:
  build failed
```

**Comment by kngwyu** [comment]
Ah, I understand.
The fix is not published and you have to use `cargo install --git https://github.com/racer-rust/racer.git` to install the latest version.

**Comment by nylo-andry** [comment]
@kngwyu Right! Thank you that works!

**Comment by jingyuexing** [comment]
>cargo install racer
  Updating crates.io index
  Downloaded racer v2.1.37
  Downloaded 1 crate (186.4 KB) in 5.38s
  Installing racer v2.1.37
  Downloaded annotate-snippets v0.8.0
  Downloaded block-buffer v0.7.3
  Downloaded derive_more v0.99.9
  Downloaded fake-simd v0.1.2
  Downloaded jobserver v0.1.21
  Downloaded memmap v0.7.0
  Downloaded parking_lot_core v0.7.2
  Downloaded rustc-ap-rustc_ast_pretty v671.0.0
  Downloaded rls-span v0.5.2
  Downloaded byte-tools v0.3.1
  Downloaded rustc-ap-rustc_fs_util v671.0.0
  Downloaded rustc-ap-rustc_parse v671.0.0
  Downloaded rustc-ap-rustc_span v671.0.0
  Downloaded arrayvec v0.5.1
  Downloaded termize v0.1.1
  Downloaded generic-array v0.12.3
  Downloaded md-5 v0.8.0
  Downloaded parking_lot v0.10.2
  Downloaded rustc-ap-rustc_arena v671.0.0
  Downloaded rustc-ap-rustc_feature v671.0.0
  Downloaded rustc-ap-rustc_macros v671.0.0
  Downloaded crossbeam-utils v0.6.6
  Downloaded rustc-hash v1.1.0
  Downloaded crossbeam-queue v0.1.2
  Downloaded getopts v0.2.21
  Downloaded once_cell v1.4.0
  Downloaded racer-interner v0.1.0
  Downloaded rustc-ap-rustc_graphviz v671.0.0
  Downloaded rustc-ap-rustc_session v671.0.0
  Downloaded scoped-tls v1.0.0
  Downloaded sha-1 v0.8.2
  Downloaded stacker v0.1.10
  Downloaded opaque-debug v0.2.3
  Downloaded rustc-ap-rustc_data_structures v671.0.0
  Downloaded ena v0.14.0
  Downloaded rustc-rayon-core v0.3.0
  Downloaded humantime v2.0.1
  Downloaded psm v0.1.11
  Downloaded rustc-ap-rustc_lexer v671.0.0
  Downloaded block-padding v0.1.5
  Downloaded measureme v0.7.1
  Downloaded rustc-ap-rustc_index v671.0.0
  Downloaded digest v0.8.1
  Downloaded rustc-ap-rustc_ast v671.0.0
  Downloaded typenum v1.12.0
  Downloaded rustc-ap-rustc_errors v671.0.0
  Downloaded lazycell v1.3.0
  Downloaded racer-cargo-metadata v0.1.1
  Downloaded rustc-ap-rustc_target v671.0.0
  Downloaded rustc-rayon v0.3.0
  Downloaded rustc-ap-rustc_serialize v671.0.0
  Downloaded env_logger v0.7.1
  Downloaded 52 crates (1.5 MB) in 36.29s
   Compiling autocfg v1.0.0
   Compiling cfg-if v0.1.10
   Compiling winapi v0.3.9
   Compiling unicode-xid v0.2.1
   Compiling proc-macro2 v1.0.19
   Compiling lazy_static v1.4.0
   Compiling maybe-uninit v2.0.0
   Compiling semver-parser v0.7.0
   Compiling scopeguard v1.1.0
   Compiling syn v1.0.38
   Compiling byteorder v1.3.4
   Compiling libc v0.2.74
   Compiling cc v1.0.58
   Compiling smallvec v1.4.2
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> C:\Users\Jingyuexing\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-1.4.2\src\lib.rs:74:32
   |
74 | #![cfg_attr(feature = "union", feature(untagged_unions))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> C:\Users\Jingyuexing\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-1.4.2\src\lib.rs:77:37
   |
77 | #![cfg_attr(feature = "may_dangle", feature(dropck_eyepatch))]
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0554`.
error: could not compile `smallvec`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `racer v2.1.37`, intermediate artifacts can be found at `C:\Users\JINGYU~1\AppData\Local\Temp\cargo-installN7ff7t`

Caused by:
  build failed

**Comment by jingyuexing** [comment]
<summary>
    <details>
        ```
>cargo install racer
    Updating crates.io index
  Downloaded racer v2.1.37
  Downloaded 1 crate (186.4 KB) in 5.38s
  Installing racer v2.1.37
  Downloaded annotate-snippets v0.8.0
  Downloaded block-buffer v0.7.3
  Downloaded derive_more v0.99.9
  Downloaded fake-simd v0.1.2
  Downloaded jobserver v0.1.21
  Downloaded memmap v0.7.0
  Downloaded parking_lot_core v0.7.2
  Downloaded rustc-ap-rustc_ast_pretty v671.0.0
  Downloaded rls-span v0.5.2
  Downloaded byte-tools v0.3.1
  Downloaded rustc-ap-rustc_fs_util v671.0.0
  Downloaded rustc-ap-rustc_parse v671.0.0
  Downloaded rustc-ap-rustc_span v671.0.0
  Downloaded arrayvec v0.5.1
  Downloaded termize v0.1.1
  Downloaded generic-array v0.12.3
  Downloaded md-5 v0.8.0
  Downloaded parking_lot v0.10.2
  Downloaded rustc-ap-rustc_arena v671.0.0
  Downloaded rustc-ap-rustc_feature v671.0.0
  Downloaded rustc-ap-rustc_macros v671.0.0
  Downloaded crossbeam-utils v0.6.6
  Downloaded rustc-hash v1.1.0
  Downloaded crossbeam-queue v0.1.2
  Downloaded getopts v0.2.21
  Downloaded once_cell v1.4.0
  Downloaded racer-interner v0.1.0
  Downloaded rustc-ap-rustc_graphviz v671.0.0
  Downloaded rustc-ap-rustc_session v671.0.0
  Downloaded scoped-tls v1.0.0
  Downloaded sha-1 v0.8.2
  Downloaded stacker v0.1.10
  Downloaded opaque-debug v0.2.3
  Downloaded rustc-ap-rustc_data_structures v671.0.0
  Downloaded ena v0.14.0
  Downloaded rustc-rayon-core v0.3.0
  Downloaded humantime v2.0.1
  Downloaded psm v0.1.11
  Downloaded rustc-ap-rustc_lexer v671.0.0
  Downloaded block-padding v0.1.5
  Downloaded measureme v0.7.1
  Downloaded rustc-ap-rustc_index v671.0.0
  Downloaded digest v0.8.1
  Downloaded rustc-ap-rustc_ast v671.0.0
  Downloaded typenum v1.12.0
  Downloaded rustc-ap-rustc_errors v671.0.0
  Downloaded lazycell v1.3.0
  Downloaded racer-cargo-metadata v0.1.1
  Downloaded rustc-ap-rustc_target v671.0.0
  Downloaded rustc-rayon v0.3.0
  Downloaded rustc-ap-rustc_serialize v671.0.0
  Downloaded env_logger v0.7.1
  Downloaded 52 crates (1.5 MB) in 36.29s
   Compiling autocfg v1.0.0
   Compiling cfg-if v0.1.10
   Compiling winapi v0.3.9
   Compiling unicode-xid v0.2.1
   Compiling proc-macro2 v1.0.19
   Compiling lazy_static v1.4.0
   Compiling maybe-uninit v2.0.0
   Compiling semver-parser v0.7.0
   Compiling scopeguard v1.1.0
   Compiling syn v1.0.38
   Compiling byteorder v1.3.4
   Compiling libc v0.2.74
   Compiling cc v1.0.58
   Compiling smallvec v1.4.2
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> C:\Users\Jingyuexing\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-1.4.2\src\lib.rs:74:32
   |
74 | #![cfg_attr(feature = "union", feature(untagged_unions))]
   |                                ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> C:\Users\Jingyuexing\.cargo\registry\src\github.com-1ecc6299db9ec823\smallvec-1.4.2\src\lib.rs:77:37
   |
77 | #![cfg_attr(feature = "may_dangle", feature(dropck_eyepatch))]
   |                                     ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0554`.
error: could not compile `smallvec`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `racer v2.1.37`, intermediate artifacts can be found at `C:\Users\JINGYU~1\AppData\Local\Temp\cargo-installN7ff7t`

Caused by:
  build failed

C:\Users\Jingyuexing>cargo show
error: no such subcommand: `show`

        Did you mean `doc`?

>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Jingyuexing\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.45.2 (d3fb005a3 2020-07-31)


>rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-gnu'
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: checking for self-updates

   stable-x86_64-pc-windows-gnu unchanged - rustc 1.45.2 (d3fb005a3 2020-07-31)
  stable-x86_64-pc-windows-msvc unchanged - rustc 1.45.2 (d3fb005a3 2020-07-31)

info: cleaning up downloads & tmp directories
```
    </details>
</summary>

**Comment by ThoenigAdrian** [comment]
@kngwyu I think this command you posted might now be out of date 
```
    cargo install --git https://github.com/racer-rust/racer.git
```

as this fails with: 

```
C:\Users\user\.rustup\toolchains\nightly-x86_64-pc-windows-msvc>cargo.exe install --git https://github.com/racer-rust/racer.git
    Updating git repository `https://github.com/racer-rust/racer.git`
error: multiple packages with binaries found: racer, test-crate3
```

I could get rid of this error by using, this command instead:

```
C:\Users\user\.rustup\toolchains\nightly-x86_64-pc-windows-msvc>cargo.exe install --git https://github.com/racer-rust/racer.git racer
```
note the additional racer at the end.

But even after adjusting for this, i get the same installation error as @jingyuexing .
I think this error message makes no sense as I am explictily using the nigthly version . Which can be seen by the path **nightly-x86_64-pc-windows-msvc** . 

But still it fails with : 

```
error[E0554]: `#![feature]` may not be used on the stable release channel
```
