### ISSUE TITLE
Explain how to change omnifunc key bindings in README

### ISSUE THREAD

**Issue by matu3ba** [racer-rust/racer#1089]
[Here](https://vi.stackexchange.com/questions/12394/change-keybinding-for-up-down-when-in-vim-popup) it is explained to change keybinding for autocompletion.
Is it okay to add to the README ? The default key bindings are inconvenient for fast  typing.

`inoremap <expr> <C-j> pumvisible() ? "\<C-n>" : "\<C-j>"`
`inoremap <expr> <C-k> pumvisible() ? "\<C-p>" : "\<C-k>"`

**Comment by matu3ba** [comment]
A wrapper function could also provide them in the library.

**Comment by matu3ba** [comment]
One might want to remap the omnifunc call as well with
inoremap <expr> <C-l><C-l> pumvisible() ? "\<C-l><C-l>" : "\<C-x><C-o>"`

**Comment by kngwyu** [comment]
Please file an issue at https://github.com/racer-rust/vim-racer
