### ISSUE TITLE
Fails to compile as a library due to rustc-ap-rustc_span-654.0.0

### ISSUE THREAD

**Issue by nitsuga5124** [racer-rust/racer#1109]
https://pastebin.com/cGhjmdHx
"error[E0407]: method `replace_one` is not a member of trait `std::iter::Step`"

**Comment by Xanewok** [comment]
Should be fixed with https://github.com/racer-rust/racer/pull/1110

**Comment by nitsuga5124** [comment]
Updating nightly and using the latest release with the patch #1110 fixed this issue.
