### ISSUE TITLE
[question] Why require nightly?

### ISSUE THREAD

**Issue by jsoo1** [racer-rust/racer#1116]
Hello and thanks for racer!

I am looking to manage my rust tooling through guix and nix instead of via rustup. Guix in particular does not have a nightly toolchain. Is there a reason nightly is required to build from source?  Thanks a lot!

**Comment by jsoo1** [comment]
Hmm, thinking about it now and after learning more, is nightly required because rustc itself requires nightly?

**Comment by kngwyu** [comment]
Yeah, it's because of `rustc-ap-syntax`
