### ISSUE TITLE
Build failing with cargo +nightly

### ISSUE THREAD

**Issue by Pancf** [racer-rust/racer#1154]
I encountered errors like that

>error[E0658]: use of unstable library feature 'array_value_iter'
   --> /Users/Pancf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_arena-702.0.0/src/lib.rs:134:40
    |
134 | impl<T, const N: usize> IterExt<T> for std::array::IntoIter<T, N> {
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #65798 <https://github.com/rust-lang/rust/issues/65798> for more information
    = help: add `#![feature(array_value_iter)]` to the crate attributes to enable
>error[E0658]: use of unstable library feature 'array_value_iter_slice'
   --> /Users/Pancf/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_arena-702.0.0/src/lib.rs:144:18
    |
144 |             self.as_slice().as_ptr().copy_to_nonoverlapping(start_ptr, len);
    |                  ^^^^^^^^
    |
    = note: see issue #65798 <https://github.com/rust-lang/rust/issues/65798> for more information
    = help: add `#![feature(array_value_iter_slice)]` to the crate attributes to enable
>error: aborting due to 2 previous errors
>For more information about this error, try `rustc --explain E0658`.
>error: could not compile `rustc-ap-rustc_arena`
>To learn more, run the command again with --verbose.
>warning: build failed, waiting for other jobs to finish...
>error: build failed

Env:
macOS
rustup 1.23.1 (3df2264a9 2020-11-30)
rustc 1.49.0 (e1884a8e3 2020-12-29)
rustc 1.51.0-nightly (04caa632d 2021-01-30)
cargo 1.49.0 (d00d64df9 2020-12-05)
cargo 1.51.0-nightly (c3abcfe8a 2021-01-25)

**Comment by calebcartwright** [comment]
Fixed in #1153, though you'll need a newer nightly (use `--force` with `rustup update`)

**Comment by look** [comment]
Thanks, I just ran into this too and running `rustup update --force nightly` and then re-running `cargo +nightly install racer` fixed it for me. 🙇
