### ISSUE TITLE
Emacs: annotations don't appear on the first completion

### ISSUE THREAD

**Issue by ane** [racer-rust/racer#203]
When completing, the annotations don't appear initially, you have to browse through the candidates to get them to appear. Specifically:
1. Type `std::io::` and then <kbd>TAB</kbd>
2. No annotations appear
3. Press <kbd>M-n</kbd> to select next
4. Annotations appear

I fiddled with the completion function in racer.el and I found out that if you remove the `(when (looking-back "[a-zA-Z <..>")` bit around the cl-case in the completion command, the annotations appear immediately. 

I don't understand what causes that behaviour: does it get called with an empty completion buffer, so on the first try `looking-back` returns false? Removing it altogether seemed to fix the issue. Unless this is desired behaviour!

Possible fix:
1. Remove surrounding `when` expression in `race-company-complete`
2. Re-evaluate with <kbd>C-M-x</kbd>
3. Go complete something
4. Annotations appear immediately.

**Comment by ane** [comment]
There seems to be an alternative way to implement the prefix position lookup: https://github.com/company-mode/company-mode/wiki/Writing-backends#advanced-example but I don't know exactly how that differns from `racer--prefix`.

**Comment by birkenfeld** [comment]
This is fixed since the merge of #350.
