### ISSUE TITLE
Screenshot example out of date

### ISSUE THREAD

**Issue by aaronkavlie-wf** [racer-rust/racer#245]
The hashmap import path [has changed](https://doc.rust-lang.org/std/collections/hash_map/struct.HashMap.html#examples) since the example screenshot was taken.

**Comment by phildawes** [comment]
Thanks @aaronkavlie-wf. I think it changed a while ago but for a while rust apis were changing every few days so I didn't fix. I'll change this at some point, but it's not top priority for me at the moment.

**Comment by TedDriggs** [comment]
The screenshots on the homepage no longer show import paths, as best I can tell.
