### ISSUE TITLE
Vim Plugin Feature Request: 'K' on a keyword should display that keyword's documentation

### ISSUE THREAD

**Issue by arnm** [racer-rust/racer#280]
I have noticed that in many language oriented vim plugins the `K` (capital k) binding when in normal mode provides the documentation for the keyword under the cursor.

This would be a very neat feature to have.

Currently, `gd` takes you to the source code where you could also look at the documentation but sometimes I don't care about the implementation of something and just want to know how to use it.

I'm not sure if racer is capable of searching just for documentation but I don't think it would be too hard to implement since it can already find the source code associated with the keyword.

**Comment by estebank** [comment]
This can be closed since https://github.com/racer-rust/vim-racer/pull/42
