### ISSUE TITLE
autocomplete std macros?

### ISSUE THREAD

**Issue by colin-kiegel** [racer-rust/racer#310]
A new feature idea :-)
- support for autocompletion of (std) macros http://doc.rust-lang.org/std/#macros
- support for find-definition of (std) macros?

**Comment by whirm** [comment]
Are there any plans on working on this? I'm a rust newbie and it would be really useful to have better auto completion and doc discovery.

**Comment by TedDriggs** [comment]
Technically #389 is newer and more scoped than this ticket, but the comment thread on it better explains the status of this request so I'm closing this in favor of that issue.
