### ISSUE TITLE
Only complete if at end of symbol

### ISSUE THREAD

**Issue by gsingh93** [racer-rust/racer#340]
In the emacs mode, `racer-complete-or-indent` starts completion regardless of the position of point. This causes problems, because if point is before the first character of a line, most users would expect tab to indent, not trigger auto completion. However, if at least one candidate is found, auto completion is triggered.

It makes more sense to check if the user is at the end of a symbol boundary before triggering completion, as described in the second example [here](http://www.emacswiki.org/emacs/CompanyMode#toc9).

**Comment by birkenfeld** [comment]
`racer-complete-or-indent` is now gone. `company-indent-or-complete-common`, which I use for binding TAB now, seems to do what you (and I) want.

**Comment by Wilfred** [comment]
I think this can be closed. Please open new Emacs-related issues on https://github.com/racer-rust/emacs-racer :)
