### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by marvelm** [racer-rust/racer#348]
I suggested this solution in https://github.com/phildawes/racer/issues/343#issuecomment-133105777. For the channel to be effective, a few things are needed:
- [ ] Volunteers to help out in certain time zones
- [ ] A code of conduct to prevent abuse
- [x] A logger like [BotBot.me](https://botbot.me) to allow newcomers to search through previous discussions.

**Comment by Shougo** [comment]
Hmmm....
I think gitter room is better.

**Comment by marvelm** [comment]
Rust has a channel on moznet with 967 people at this time. I think we might benefit from some of those users helping out.

**Comment by svenstaro** [comment]
So is there an IRC as of now?

**Comment by TedDriggs** [comment]
The maintainers all seem to be in the #rust-dev-tools room on irc.mozilla.org, so you can find us there.
