### ISSUE TITLE
Homebrew Package

### ISSUE THREAD

**Issue by mdedetrich** [racer-rust/racer#379]
Not sure about other OS environments, but we should provide a homebrew distribution, especially for editors (such as Atom) that don't provide their own package management system and rely on external binaries

**Comment by tomjakubowski** [comment]
In general there seem to be many unanswered questions about how best to package Rust applications like racer for distribution by package managers like Homebrew and apt.  I'd like to see racer leading the charge to answer them!

> especially for editors (such as Atom) that don't provide their own package management system

I thought Atom had its own package manager, at least it did when I installed it. What do you mean?

**Comment by mdedetrich** [comment]
> In general there seem to be many unanswered questions about how best to package Rust applications like racer for distribution by package managers like Homebrew and apt. I'd like to see racer leading the charge to answer them!

Awesome! In modern times I just have a real distaste for manual package management

> I thought Atom had its own package manager, at least it did when I installed it. What do you mean?

Atom does have its own package manager, but they act more like interfaces/bridges. You will see that many language implementations for things like autocomplete refer to an already installed binary that provides that autocompletion (rather than packaging it with the Atom Package)

Current examples are Scala (ensime), C# (omnisharp). I am sure there are others

**Comment by TedDriggs** [comment]
We distribute racer via cargo; I'm not sure we need a separate homebrew package.

**Comment by mdedetrich** [comment]
This is irrelevant, you can now install rust with racer (using the `--with-racer` flag) with homebrew
