### ISSUE TITLE
Use rustc's macro expansion flag called --pretty=expanded

### ISSUE THREAD

**Issue by yaskhan** [racer-rust/racer#407]
http://stackoverflow.com/questions/28580386/how-do-i-see-the-expanded-macro-code-thats-causing-my-compile-error

Useful for modules and extern crates. But, i think this not work for current editing file.

**Comment by TedDriggs** [comment]
Using that flag would add an unacceptable delay to racer's operation. RLS is doing much more in the "comprehending macros" space, so I'm closing this issue in favor of their work.
