### ISSUE TITLE
Comment the code!

### ISSUE THREAD

**Issue by vadimcn** [racer-rust/racer#440]
So the other day I felt an urge to contribute a feature or two to Racer 'cause it's a cool and useful tool. 
But then I looked at the source... and went like "Gah, I am gonna to have to spend several evenings reverse-engineering what's going on here before I can contribute anything.  Meh, don't feel like it today :tired_face:".  And so I went back to browsing Reddit.  
True story ^^^.  

I urge you to consider spending some time on commenting your code and writing up a high-level overview of how Racer operates.  I think you'd be getting more non-trivial PRs if this code were more approachable.

**Comment by Jonesey13** [comment]
In defence of racer, I really liked the logging features that this library has. It allowed me to dive in and see how the program ticks. I wouldn't have been able to understand what's going on (or contribute) without the logs! 

But of course, adding a quick overview to the top of each source file wouldn't hurt!

**Comment by bruno-medeiros** [comment]
For me, it helped me to run racer with the interactive debugger. The logs too, since the value of complex types can't usually be displayed in the debugger (I miss that in Java! :sweat_smile: ).

That said, a high level overview would have been nice, I've only just touched the surface of racer...

**Comment by vadimcn** [comment]
Logging is definitely helpful, but still, it answers only the what, but not the why.

**Comment by TedDriggs** [comment]
This is good feedback, but it's an ongoing process and not something that will ever be "done". To that end, I'm closing this issue out.

That said, we'd welcome any PRs that add comments and/or doc comments. We're also making a (slow) effort to improve commentary as we do other work.
