### ISSUE TITLE
build error with time out 

### ISSUE THREAD

**Issue by windyslove** [racer-rust/racer#478]
-OEM:~/Development/racer-master$ cargo build --release -v
 Downloading log v0.3.4
 Downloading kernel32-sys v0.2.1
unable to get packages from source

Caused by:
  Failed to download package `kernel32-sys v0.2.1` from https://crates.io/api/v1/crates/kernel32-sys/0.2.1/download

Caused by:
  Timeout was reached

how can i fix this,any one can help?
i run this command on ubuntu 14.10
![Uploading 2016-01-17 00-23-04屏幕截图.png…]()

**Comment by phildawes** [comment]
This sounds like a network communication problem - your computer was unable to download packages from crates.io.
