### ISSUE TITLE
Wrong multirust directory on Windows

### ISSUE THREAD

**Issue by hban** [racer-rust/racer#503]
It looks like Racer is looking in wrong place for multirust on Windows. `multirust-rs` will not install itself directly in user's home directory, but in in `%LocalAppData%\.multirust`. Relevant piece of code:  [`rust_install::util::get_local_data_path`](https://github.com/Diggsey/multirust-rs/blob/1a9c904/rust-install/src/utils/mod.rs#L595).

**Comment by TedDriggs** [comment]
multirust is deprecated in favor of rustup now
