### ISSUE TITLE
Does not autocomplete iron

### ISSUE THREAD

**Issue by Emilgardis** [racer-rust/racer#528]
Currently racer fails to autocomplete iron, no clue why.
[Gist](https://gist.github.com/Emilgardis/65b72030cc6718364cd08d460301edb2) for all related files.
#499 may be related.

**Comment by lem0nify** [comment]
@Emilgardis It does. It just can't parse imports when you write `use module::something::*;` such as `use iron::prelude::*;`. So, if you will import symbols manually like `use iron::Iron;`, it will AC fine.

**Comment by TedDriggs** [comment]
This looks to be a duplicate of #499, unless I'm missing something. Closing this to focus the discussion there.
