### ISSUE TITLE
Racer doesn't seem to work for crates that were added via git

### ISSUE THREAD

**Issue by MaikKlein** [racer-rust/racer#581]
This could also possibly be a problem with `Youcompleteme`.

Testcase:

```
extern crate vulkano;

fn main() {
    println!("Hello, world!");
}
```

and

```
[package]
name = "rtest"
version = "0.1.0"

[dependencies]
vulkano = { git = "https://github.com/tomaka/vulkano" }
```

Autocomplete nor goto definion with `YcmCompleter GoTo` work with vulkano.

Works with

```
[package]
name = "rtest"
version = "0.1.0"

[dependencies]
vulkano = "0.1.0"
```

**Comment by genneth** [comment]
Not totally true --- it does seem to work sometimes, but not always. Have just loaded up the tutorial example from future-rs, using VS Code and RustyCode: it finds things in future, but not future_io.

**Comment by MaikKlein** [comment]
Any update? Is there a workaround?

**Comment by MaikKlein** [comment]
I think it might be related to workspaces and git. I just tried a few crates with workspaces and racer could complete none of them, if they were added with git.

**Comment by kngwyu** [comment]
I think #855 fixed this.
@MaikKlein
Can you reproduce it in racer >= 2.1.0?

**Comment by MaikKlein** [comment]
@kngwyu Yes that fixed it. Sorry I thought I already was on the newest version.
