### ISSUE TITLE
Crash on master branch

### ISSUE THREAD

**Issue by hotpxl** [racer-rust/racer#625]
I have the following piece of code:

``` rust
use std::io;

struct Poll {
}

impl Poll {
    pub fn new() -> io::Result<Poll> {
        Ok(Poll {})
    }
}

fn main() {
    let poll = Poll::new();
    poll.
}
```

Completing on 14:9, just after the dot in `poll.`. Using racer installed from cargo (1.2.10), it gives me a list of options (correct behavior), but using master, it just crashes with `do not lie on character boundary', src/libcore/str/mod.rs:1694`.

Second problem. The other day I was completing the "mio" library. It paniced when calling [this function](https://github.com/phildawes/racer/commit/acd81ba13b9a09274c9c8947d6fa287d17561dd1#diff-2ae8a425d028c7f1f13f4e701b510d1aR408). The panic was on line 424 where an unsigned integer subtract overflows. But after some digging, when calling function `get_type_of_typedef`, it was trying to find the type of `io::Result`, but `fpath` argument was passed the file path of the mio library. I think that might be the cause of the problem, but haven't figured out how to solve it.

**Comment by TedDriggs** [comment]
@hotpxl are you able to repro this on Racer 2.0.8?

**Comment by hotpxl** [comment]
I've not written rust for a long time. back then racer has a lot of hardcoding and matching that is not complete. i'm sure things have changed for the better and i'll close this issue now :)
