### ISSUE TITLE
Character literals containing more than one source character are incorrectly masked into invalid syntax

### ISSUE THREAD

**Issue by Arnavion** [racer-rust/racer#628]
- rust 1.12.0 (3191fbae9 2016-09-23) (via rustup, stable-x86_64-pc-windows-msvc toolchain)
- racer 1.2.10 (latest via `cargo install racer`), also [current git master](https://github.com/phildawes/racer/commit/b36a9a6af862a63db9397e76abc3cb2013751b8d)

`C:\Users\Arnavion\Desktop\test.rs`

``` rust
fn main() {
    let mut splits = "555".split_terminator('\n');
    splits.pop()
}
```

`SET RUST_LOG=racer=debug racer find-definition 3 12 C:\Users\Arnavion\Desktop\test.rs`

(`(3, 12)` is in the middle of `pop`)

This panics with:

```
DEBUG:racer::core: find_definition_ for |"splits"| |"pop"| Field
DEBUG:racer::ast: visit_expr expr(4294967295: splits)
DEBUG:racer::ast: expr is a path P[splits]
DEBUG:racer::ast: resolve_ast_path P[splits]
DEBUG:racer::nameres: resolve_path_with_str P[splits]
DEBUG:racer::nameres: resolve_path P[splits] Some("C:\\Users\\Arnavion\\Desktop\\test.rs") 75 ExactMatch
DEBUG:racer::nameres: resolve_name splits Some("C:\\Users\\Arnavion\\Desktop\\test.rs") 75 ExactMatch BothNamespaces
DEBUG:racer::nameres: search_local_scopes PathSegment { name: "splits", types: [] } Some("C:\\Users\\Arnavion\\Desktop\\test.rs") 75 ExactMatch BothNamespaces
DEBUG:racer::nameres: searching scope BothNamespaces start: 11 point: 75 'splits' Some("C:\\Users\\Arnavion\\Desktop\\test.rs") ExactMatch local: true, session: Session("C:\\Users\\Arnavion\\Desktop\\test.rs", "C:\\Users\\Arnavion\\Desktop\\test.rs")
DEBUG:racer::matchers: match_pattern_let point is 24
DEBUG:racer::typeinf: get_type_of match Match ["splits", Some("C:\\Users\\Arnavion\\Desktop\\test.rs"), 24, true, Let, [], [] |let mut splits = "555".split_terminator('\n');|]
DEBUG:racer::typeinf: get_type_of_let_expr calling parse_let |let mut splits = "   ".split_terminator('  ');|
bogofile:1:41: 1:43 error: character literal may only contain one codepoint: '
bogofile:1 let mut splits = "   ".split_terminator('  ');
                                                   ^~
thread 'main' panicked at 'Box<Any>', C:\Users\Arnavion\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_syntax-0.32.0\src\parse\lexer/mod.rs:1283
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

The contents of the string and the string literal appear to have been replaced by space characters (one for each original character). So `\n` has become a character literal containing two spaces, which is a syntax error and triggers [this panic.](https://github.com/serde-rs/syntex/blob/90985eacb8c129bdb743a722f4fc6b16e2cc268b/syntex_syntax/src/parse/lexer/mod.rs#L1279-L1281)

~~I'm trying to investigate where this is breaking - racer or syntex_syntax or...~~

---

Edit: I updated output above with the debug output, and it seems something went wrong between `DEBUG:racer::typeinf: get_type_of match` and `DEBUG:racer::typeinf: get_type_of_let_expr`

---

Edit 2: It seems to be happening in `scopes::mask_comments` when it's called from `session::load_file_and_mask_comments`. I annotated it like this:

``` rust
pub fn mask_comments(src: Src) -> String {
    println!("aaa {:?}", src);
    let mut result = String::with_capacity(src.len());
    let buf_byte = &[b' '; 128];
    let buffer = from_utf8(buf_byte).unwrap();
    let mut prev: usize = 0;
    for (start, end) in src.chunk_indices() {
        println!("bbb {:?}", result);
        for _ in 0..((start-prev)/128) { result.push_str(buffer); }
        println!("ccc {:?}", result);
        result.push_str(&buffer[..((start-prev)%128)]);
        println!("ddd {:?}", result);
        result.push_str(&src[start..end]);
        println!("eee {:?}", result);
        prev = end;
    }
    println!("fff {:?}", result);
    result
}
```

and I see:

```
aaa Src { src: IndexedSource { code: "fn main() {\n    let mut splits = \"555\".split_terminator(\'\\n\');\n    splits.pop()\n}\n", idx: [(0, 34), (37, 57), (59, 82)] }, from: 0, to: 75 }
bbb ""
ccc ""
ddd ""
eee "fn main() {\n    let mut splits = \""
bbb "fn main() {\n    let mut splits = \""
ccc "fn main() {\n    let mut splits = \""
ddd "fn main() {\n    let mut splits = \"   "
eee "fn main() {\n    let mut splits = \"   \".split_terminator(\'"
bbb "fn main() {\n    let mut splits = \"   \".split_terminator(\'"
ccc "fn main() {\n    let mut splits = \"   \".split_terminator(\'"
ddd "fn main() {\n    let mut splits = \"   \".split_terminator(\'  "
eee "fn main() {\n    let mut splits = \"   \".split_terminator(\'  \');\n    splits.p"
fff "fn main() {\n    let mut splits = \"   \".split_terminator(\'  \');\n    splits.p"
```

---

Edit 3: So, looking at the function that generates the indices (`codecleaner::code_chunks`) I see that it's intentional that string contents are to be omitted:

``` rust
/// Returns indices of chunks of code (minus comments and string contents)
```

However this logic is broken for character literals that are made up of more than one "source" character, eg character literals that contain escapes like `'\n'`.

I'll update the bug title.

**Comment by jwilm** [comment]
Thanks for the thorough report! I probably won't have time this weekend to look at this bug, but I'll add it to the list! Depending on how ambitious you're feeling, a test for this behavior would be super helpful.

Thanks again :smile:

**Comment by Arnavion** [comment]
Tests in #630

As for a possible fix, I'm still trying to figure out why there's a need to mask string contents at all.

**Comment by jwilm** [comment]
The test looks great. Thanks so much for adding that.

I don't actually know why character literal contents are masked at all. Have you tried looking into the history of the mask comments function? Otherwise, maybe @birkenfeld or @phildawes have an answer as to why.

**Comment by Arnavion** [comment]
It was introduced in https://github.com/phildawes/racer/commit/7ee5e79 but there's no context around it :) Let me see what breaks in tests if I remove it.

**Comment by jwilm** [comment]
This is in the FileCache docs:

> where "masked" is a version with comments and strings replaced by spaces, so that they aren't found when scanning the source for signatures.

I'm not sure which scanning it refers to, but it certainly seems like character literals should be ignored in both cases.

**Comment by kngwyu** [comment]
Closed since I can't reproduce in current version.
