### ISSUE TITLE
Consecutive newline characters missing in docstring

### ISSUE THREAD

**Issue by qzed** [racer-rust/racer#683]
## Description
Racer seems to either remove consecutive newline characters or ignore (inner) empty lines, thus breaking markdown rendering in certain places, for example `std::path`.

### The rust source-code:
```rust
//! * The root directory component represents a separator that designates
//!   starting from root. For example, `/a/b` has a root directory component
//!   followed by normal components `a` and `b`.
//!
//! On Windows, an additional component type comes into play:
//!
//! * Prefix components, of which there is a large variety. For example, `C:`
//! and `\\server\share` are prefixes. The path `C:windows` has a prefix
//! component `C:` and a normal component `windows`; the path `C:\windows` has a
//! prefix component `C:`, a root directory component, and a normal component
//! `windows`.
//!
//! ### Normalization
//!
//! Aside from splitting on the separator(s), there is a small amount of
//! "normalization":
```

### The returned doc-string is (excerpt with un-escaped special characters):
```markdown
* The root directory component represents a separator that designates
  starting from root. For example, `/a/b` has a root directory component
  followed by normal components `a` and `b`.
On Windows, an additional component type comes into play:
* Prefix components, of which there is a large variety. For example, `C:`
and `\\server\share` are prefixes. The path `C:windows` has a prefix
component `C:` and a normal component `windows`; the path `C:\windows` has a
prefix component `C:`, a root directory component, and a normal component
`windows`.
### Normalization
Aside from splitting on the separator(s), there is a small amount of
"normalization":
```

### Displaying the above:
> * The root directory component represents a separator that designates
>   starting from root. For example, `/a/b` has a root directory component
>   followed by normal components `a` and `b`.
> On Windows, an additional component type comes into play:
> * Prefix components, of which there is a large variety. For example, `C:`
> and `\\server\share` are prefixes. The path `C:windows` has a prefix
> component `C:` and a normal component `windows`; the path `C:\windows` has a
> prefix component `C:`, a root directory component, and a normal component
> `windows`.
> ### Normalization
> Aside from splitting on the separator(s), there is a small amount of
> "normalization":

### How it _should_ look:
> * The root directory component represents a separator that designates
>   starting from root. For example, `/a/b` has a root directory component
>   followed by normal components `a` and `b`.
>
> On Windows, an additional component type comes into play:
>
> * Prefix components, of which there is a large variety. For example, `C:`
> and `\\server\share` are prefixes. The path `C:windows` has a prefix
> component `C:` and a normal component `windows`; the path `C:\windows` has a
> prefix component `C:`, a root directory component, and a normal component
> `windows`.
>
> ### Normalization
>
> Aside from splitting on the separator(s), there is a small amount of
> "normalization":

In this example, the two separated lists get merged due to a missing newline character.

**Comment by jwilm** [comment]
Thanks for the thorough issue report!

**Comment by qzed** [comment]
I'm happy to help. It seems like this is only related to the module documentation (i. e. the `find_mod_doc` function) and to this particular [line](https://github.com/phildawes/racer/blob/e937058404b2034625ac7ed438d07514ca0eacf1/src/racer/matchers.rs#L726). Removing the space after `//!` should fix it, I'll try that out and respond.

**Comment by qzed** [comment]
I have added a PR which applies the fix described above.
