### ISSUE TITLE
`find-definition` doesn't correctly find closure parameters

### ISSUE THREAD

**Issue by mlalic** [racer-rust/racer#695]
Two minimal ways to reproduce the issue.

For:
```rust
fn main() {
    let y = Some(5);
    y.map(|x| x + 1);
}
```

Looking for the definition of `x` in the closure body yields nothing.
```
mlalic@gallifrey:~/src/racer/target/debug$ ./racer find-definition 3 15 test.rs
END
```

For:
```rust
fn main() {
    let x = Some(5);
    x.map(|x| x + 1);
}
```

Again, looking for the definition of `x` *from the closure body* this time yields the `x` in the enclosing scope, which is arguably worse than not finding anything.

```
mlalic@gallifrey:~/src/racer/target/debug$ ./racer find-definition 3 15 test.rs
MATCH x,2,8,test.rs,Let,let x = Some(5);
END
```

**Comment by TedDriggs** [comment]
This appears to be fixed by #697.
