### ISSUE TITLE
Implement "find usages"

### ISSUE THREAD

**Issue by vext01** [racer-rust/racer#714]
Hi,

A feature that I am used to from jedi-vim:

```
Usages <leader>n (shows all the usages of a name)
```

I.e. the opposite of racer's `find-definition` command. This is very useful when editing code to find call-sites of a function. Is there scope to add this to racer so that editor plugins like deoplete-rust and vim-racer can make use of this?

CC @Shougo @sebastianmarkow

Thanks

**Comment by TedDriggs** [comment]
This would be cool, but _might_ be hard to implement (??). I have an idea on how to do it, but I'd want feedback from someone more knowledgeable before I start down this road:

Assume the cursor is sitting on an identifier ("the identifier").

1. Find the definition range of the identifier.
1. Search for all uses of that identifier, regardless of context or scope.
1. For each match, call `find-definition`. If the definition match is the same as the match in step 1, return it as a usage.

# Open Questions
1. How do you know which files to search? As a user, I'd expect it to look at the current working directory's crate or workspace; I assume racer knows this but I'm not sure how to keep it from scanning the code of all dependent crates.

**Comment by jwilm** [comment]
I think such a feature is out of scope for Racer at this point. RLS already provides this functionality.

**Comment by TedDriggs** [comment]
It does?

**Comment by TedDriggs** [comment]
As @jwilm points out, this is something that RLS is providing.
