### ISSUE TITLE
In-built support for rustup?

### ISSUE THREAD

**Issue by alexreg** [racer-rust/racer#718]
The current solution of having to manually set the `RUST_SRC_PATH` variable in one's profile is far from ideal, due to the dynamic/directory-dependent nature of toolchains. Hence, I would propose building in support for rustup into racer, so that if `RUST_SRC_PATH` is not set (or perhaps another environment variable *is* set?), it would run a `rustup` command to get the source path when it needs to, rather than taking it statically from a variable.

**Comment by zachlute** [comment]
This appears to be a dupe of #595 and can probably be closed.

**Comment by alexreg** [comment]
Maybe. Would be nice if someone could take a look at it anyway...
