### ISSUE TITLE
Racer doesn't resolve `use` statements

### ISSUE THREAD

**Issue by legolord208** [racer-rust/racer#744]
I use vim-racer.
Imagine something like this:

```Rust
use std::io;

fn main() {
    io:: // <- Complete here
}
```

Doesn't work.
To make sure it's a problem with racer and not vim-racer, I tried `racer complete "use std::io; io::"`. Still nothing. Then `fn main() { use std::io; io::`.

Yeah, you get the idea. Just won't work, no matter what

**Comment by TedDriggs** [comment]
Did you set RUST_SRC_PATH?

**Comment by legolord208** [comment]
![image](https://user-images.githubusercontent.com/12830969/27134253-506b1e86-5115-11e7-9136-5131aebdadc2.png)
Seems like it :thinking:

**Comment by TedDriggs** [comment]
Well then. Could you please try running `RUST_LOG=racer=trace racer complete 4 8 ./src/main.rs` (on mobile so I may have counted line and column numbers wrong) and share that output?

**Comment by legolord208** [comment]
........apparently that worked :thinking:

Guessing the problem was that I didn't try with using a file, only the text.  
The fault must be on vim-racer's side. Sorry for disturbing!
