### ISSUE TITLE
Racer outputs multiple-line results

### ISSUE THREAD

**Issue by AdnoC** [racer-rust/racer#746]
* Racer version: master. Also present in release 2.0.8

When completing a `const` that occurs any number of lines directly above another `const`, racer matches on not only the identifier of the const, but everything until the end of the line the second const is on as well.

# Reproducing the bug

Given a small file `example.rs`:

```rust
pub const SE



pub const A_CONST: u8 = 2
```

Get completions for the first line:

```bash
racer complete 1 12 example.rs
```

The output is:

```
PREFIX 10,12,SE
MATCH SE



pub const A_CONST,1,10,example.rs,Const,pub const SE
END
```

&nbsp;

&nbsp;

Interestingly, `Debug` output of the `Message` enum containing the match was

```
 Match("SE\n\n\n\npub const A_CONST", 1, 10, "example.rs", Const, "pub const SE")
```

So the problem seems to be caused in the completion machinery itself, which is why https://github.com/racer-rust/racer/pull/585 didn't fix it.

**Comment by Diomendius** [comment]
I had a small adventure tracking this one down, but I've fixed this and opened a pull request. I found an unrelated bug in ``is_const_fn`` in the process, too, so that's nice.
