### ISSUE TITLE
syntex_syntax causes compilation failure on rust 1.18

### ISSUE THREAD

**Issue by adrianbrink** [racer-rust/racer#752]
Hi,

[syntex_syntax](https://github.com/serde-rs/syntex) does not compile on [1.18 anymore](https://github.com/serde-rs/syntex/issues/117), which means that racer doesn't compile on 1.18. 

I am on Ubuntu 17.04

**Comment by TedDriggs** [comment]
Can you please file an issue on the syntex_syntax repo and link to it here?

**Comment by CryZe** [comment]
The latest syntex_syntax compiles just fine with 1.18. So they probably resolved the issue, but racer still uses an ancient version of syntex_syntax.

**Comment by CryZe** [comment]
I just compiled racer and it seems to compile just fine on 1.20 nightly, so I'm not quite sure where the compilation failure is supposed to be.
