### ISSUE TITLE
match prevents racer returning correct positions for enums

### ISSUE THREAD

**Issue by Wilfred** [racer-rust/racer#754]
Given the code:

```rust
enum Fruit {
    Apple = 1,
}

fn foo(ty: Fruit) -> bool {
    (1 as u8 | Fruit::Apple as u8) == Fruit::Apple as u8
}

fn bar(ty: Fruit) -> bool {
    match ty {
        Fruit::Apple |
        Fruit::Apple => {
            false
        }
    }
}
```

Racer cannot find the definition of `Fruit` when called from the body of `foo`:

```
$ RUST_SRC_PATH=/home/wilfred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src racer find-definition 6 20 foo.rs 
MATCH Fruit,6,1,foo.rs,FnArg,| Fruit::Apple as u8) == Fruit::Apple as u8 } fn bar(ty: Fruit) -> bool { match ty { Fruit::Apple |
END
```

The position returned by racer is whitespace on the wrong line.

**Comment by TedDriggs** [comment]
This seems to be another flavor of the issue #734 tried to address; it's mistaking the `|` characters for a closure. Here's the log line which shows the offending "match"

```
TRACE:racer::nameres: Found a closure declaration 72..184, about to search for
 `Fruit` in | Fruit::Apple as u8) == Fruit::Apple as u8
}

fn bar(ty: Fruit) -> bool {
    match ty {
        Fruit::Apple |
```

**Comment by Wilfred** [comment]
The really weird thing about this bug is that it occurs even when the `bar` function is commented out:

```rust
enum Fruit {
    Apple = 1,
}

fn foo(ty: Fruit) -> bool {
    (1 as u8 | Fruit::Apple as u8) == Fruit::Apple as u8
}

// fn bar(ty: Fruit) -> bool {
//     match ty {
//         Fruit::Apple |
//         Fruit::Apple => {
//             false
//         }
//     }
// }
```

However, removing the `bar` function prevents the bug.

**Comment by TedDriggs** [comment]
I think that's still a result of the closure issue. @jwilm I don't have time to do a rewrite of the closure work that's more resilient at the moment. It seems to work okay some of the time, but there are definitely edge cases like this that keep popping up. Would you rather we keep applying stopgap fixes for now, or rip it out completely?

**Comment by jwilm** [comment]
Maybe it's better to take closure support out for now? It would probably be a lot more resilient if the implementation based on regex, and that would take some time to fix.

**Comment by TedDriggs** [comment]
Sadly, I'm leaning the same way. 

cc @bkchr for awareness / in case he has time to investigate a stricter approach.

**Comment by bkchr** [comment]
Just to let you know, I began to re-implement the closure detection([https://github.com/bkchr/racer/tree/closure_detection_fixes](https://github.com/bkchr/racer/tree/closure_detection_fixes)). But I'm not that far with my implementation, but this time without regex ;) Maybe tomorrow I will find more time to work on this!

**Comment by bkchr** [comment]
I finished the implementation and opened a pull request :)
