### ISSUE TITLE
Find types for variables with inferred types through match statements

### ISSUE THREAD

**Issue by aurabindo** [racer-rust/racer#755]
Consider the following snippet:
```Rust
use std::fs::File;

fn main() {
    let f = File::open("hey");

    let f = match f {
        Ok(file) => file,
        Err(error) =>  {
            panic!("Error opening file: {:?}", error)
        }
    };
    f.
}
```
As soon as I type `f.` I'd like to be provided with the possible functions I can call on `f`. As of racer 2.0.9, this feature does not exist. 

Is this a possible feature?

**Comment by TedDriggs** [comment]
In general, racer does support type inference (and thus completions) for local variables. However, in this case your `match` statement is causing racer to lose track of the type. Offending log line is:

```
DEBUG:racer::ast: - Could not match expr node type: Match(expr(4294967295: f), [Arm { attrs: [], pats: [pat(4294967295: Ok(file))], guard: None, body: expr(4294967295: file) }, Arm { attrs: [], pats: [pat(4294967295: Err(error))], guard: None, body: expr(4294967295: { File::open("    ").unwrap() }) }])
```

**Comment by bkchr** [comment]
@TedDriggs could you assign me this issue? I already have a working prototype for type inference on matches.

**Comment by TedDriggs** [comment]
@bkchr I can't, but I'll self-assign so that people know it's assigned to someone. Look forward to the PR!
