### ISSUE TITLE
Racer perpetually at 100% CPU

### ISSUE THREAD

**Issue by TyOverby** [racer-rust/racer#757]
Racer is at 100% CPU while resolving paths.  Attached is an OSX Instruments trace showing several seconds of the behavior.

https://drive.google.com/open?id=0B3SDaVEK-4DEUFVOU3J3SFM1VG8

**Comment by jwilm** [comment]
Could you open up permissions on that file? Says I can't download.

**Comment by TyOverby** [comment]
Ah yep, sorry about that, should be good now

**Comment by Vurich** [comment]
I get this behaviour on [lunarity](https://github.com/maciejhirsz/lunarity/).

**Comment by kristate** [comment]
+1

**Comment by johalun** [comment]
+1 
racer is unusable :(  
truss on freebsd show racer scanning files and folder over and over. It freezes my Emacs for many seconds every time I try a completion or go-to-function.

**Comment by mqzry** [comment]
I have the same issue. version 2.013

**Comment by kngwyu** [comment]
Closed via #875
