### ISSUE TITLE
racer impl suggestions broken by preceding ::

### ISSUE THREAD

**Issue by mqudsi** [racer-rust/racer#763]
Working case:

testcase.rs:
```rust
fn main() {
}

struct Test {
}

impl std::
```

Executing `racer complete 7 10 testcase.rs` returns a list of completions in the std namespace.

However, prefixing `std` with `::`, as would be required within a module, results in no results:

testcase2.rs:
```rust
fn main() {
}

struct Test {
}

impl ::std::
```

Executing `racer complete 7 11 testcase2.rs` returns no results.

**Comment by TedDriggs** [comment]
Here's another repro of the same issue:

```rust
fn foo() -> ::~ {
    
}
```

This finds no completions, while removing the `::` mark finds lots of them.
