### ISSUE TITLE
Add commands to translate between racer coords and points

### ISSUE THREAD

**Issue by TedDriggs** [racer-rust/racer#770]
Racer's logging uses `Point`, an alias for `usize` which represents a location in a file. Mapping that back to human-friendly line and character numbers requires non-trivial work which makes the debug cycle unnecessarily long.

# Proposal

## Part 1: `racer point`
Add a new command `point`, which has the same syntax as `complete` or `find-definition`, e.g.

```
racer point 32 11 src/lib.rs
```

This could return `{POINT}`, though exact output format is open for discussion.

## Part 2: `racer coords`
Add a new command `coords`, which has the following syntax:

```
racer coords 295 src/lib.rs
```

This could return `{LINE}:{CHAR}`, though exact output format is open for discussion.

**Comment by jwilm** [comment]
Sounds good to me!
