### ISSUE TITLE
Add `complete` support for std lib macros such as `println!`

### ISSUE THREAD

**Issue by Dushistov** [racer-rust/racer#777]
Thanks for your tool,

I think it would be nice to complete for polular macros from std:

`println!`, `unimplemented!`, `unreachable!`, `assert!`, `assert_eq!`

**Comment by mqudsi** [comment]
I would add `eprintln` to the list, it probably wasn't around when this issue was created.

**Comment by BatmanAoD** [comment]
Also `vec!`.

**Comment by julitopower** [comment]
Is there any work being done for this?

**Comment by kngwyu** [comment]
@julitopower 
No, but I'm planning to add partial macro support(only for stdlib macros) before 2.1

**Comment by kngwyu** [comment]
Closed via #902
