### ISSUE TITLE
pub(crate) -> not completition

### ISSUE THREAD

**Issue by Dushistov** [racer-rust/racer#780]
With code like this:

```rust
struct Foo {
    a: i32,
}

impl Foo {
      pub fn f(&self) { //A
//    pub(crate) fn f(&self) {//B
        self.
    }
}
```
`racer` works fine, and show `a` and `f` as completition,
but if comment line `A` and uncommet `B` racer reports: `No completition found`

**Comment by TedDriggs** [comment]
This was fixed in v2.0.9 by #748. Please make sure you are running the latest version of racer using `cargo install racer --force`

**Comment by Dushistov** [comment]
@TedDriggs I use racer 2.0.9, so I use last version.

And this is not fixed in 2.0.9. Test case mentioned in #748 works for me,
while my test not works.

I'm going to try master.

**Comment by TedDriggs** [comment]
If it doesn't work on master, I'll reopen the issue.

**Comment by Dushistov** [comment]
@TedDriggs Thanks, it works on master.
