### ISSUE TITLE
Debian couldn`t build racer, kernel32-sys error

### ISSUE THREAD

**Issue by Crandel** [racer-rust/racer#782]
OS: Linux crandel 4.11.0-2-amd64 #1 SMP Debian 4.11.11-1 (2017-07-22) x86_64 GNU/Linux (testing)
Installed dependencies: 
* build-essential/testing,stable,unstable,now 12.3 amd64
* gcc-7/unstable,now 7.1.0-11
* clang-5.0/unstable,now 1:5.0
* binutils/unstable,now 2.29-2
* binutils-dev/unstable,now 2.29-2
* rustc --version -> rustc 1.19.0 (0ade33941 2017-07-17)
* cargo --version -> cargo 0.20.0 (a60d185c8 2017-07-13)

try to run `cargo install racer` and have this error

```
Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing racer v2.0.10
   Compiling strsim v0.6.0
   Compiling ansi_term v0.9.0
   Compiling unicode-segmentation v1.2.0
   Compiling typed-arena v1.3.0
   Compiling winapi-build v0.1.1
   Compiling bitflags v0.7.0
   Compiling libc v0.2.29
   Compiling log v0.3.8
   Compiling bitflags v0.9.1
   Compiling unicode-width v0.1.4
   Compiling winapi v0.2.8
   Compiling utf8-ranges v0.1.3
   Compiling vec_map v0.8.0
   Compiling unicode-xid v0.0.3
   Compiling term v0.4.6
   Compiling rustc-serialize v0.3.24
   Compiling regex-syntax v0.3.9
   Compiling kernel32-sys v0.2.2
   Compiling term_size v0.3.0
   Compiling memchr v0.1.11
   Compiling atty v0.2.2
error: failed to run custom build command for `kernel32-sys v0.2.2`
could not execute process `/tmp/cargo-install.alhS2sxUVX4L/release/build/kernel32-sys-5650331d936f2c92/build-script-build` (never executed)
Build failed, waiting for other jobs to finish...
error: failed to compile `racer v2.0.10`, intermediate artifacts can be found at `/tmp/cargo-install.alhS2sxUVX4L`

Caused by:
  build failed
```

**Comment by jwilm** [comment]
Builds fine for me on Debian stable:
Linux makkathran 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux

**Comment by Crandel** [comment]
@jwilm I`m glad for you, but I still have the same issue. I don`t know which dependencies I missed, can you help me?

**Comment by Gordon-F** [comment]
@Crandel Try install gcc and build-essential

**Comment by Crandel** [comment]
already installed


   - build-essential/testing,stable,unstable,now 12.3 amd64
   - gcc-7/unstable,now 7.1.0-11
   - clang-5.0/unstable,now 1:5.0
   - binutils/unstable,now 2.29-2
   - binutils-dev/unstable,now 2.29-2
   - rustc --version -> rustc 1.19.0 (0ade33941 2017-07-17)
   - cargo --version -> cargo 0.20.0 (a60d185c8 2017-07-13)


Have a nice day,
Vitaliy

**Comment by o01eg** [comment]
@Crandel Could you check if you have `noexec` flag for `/tmp` and try to install racer with --verbose.

**Comment by Crandel** [comment]
@o01eg Thank you, remove `noexec` flag for `/tmp` solve my issue
