### ISSUE TITLE
Racer shouldn't need type annotations to understand enum variants

### ISSUE THREAD

**Issue by TedDriggs** [racer-rust/racer#785]
Repro code:

```rust
fn foo() {
    let bar = Some("Hello");
    bar.unwrap_or_d~efault();
}
```

**Expected:** Completion at the cursor should find `unwrap_or_default`
**Observed:** Completion finds nothing, because it "can't find the type of an EnumVariant"

The least invasive fix seems to be identifying the call to the enum variant and resolving its parent enum type.

**Comment by kngwyu** [comment]
Closed via #825
