### ISSUE TITLE
Fail to install on pre-1.18 stable due to use of pub(crate)

### ISSUE THREAD

**Issue by deikatsuo** [racer-rust/racer#787]
![screenshot from 2017-08-13 09-37-39](https://user-images.githubusercontent.com/8337409/29245653-4c506da4-800b-11e7-8f71-978705ce513c.png)

**Comment by deikatsuo** [comment]
#solved

**Comment by EdouardParis** [comment]
I have the same error with rustc 1.16.0
This issue should not be labeled as solved

**Comment by TedDriggs** [comment]
The usage of `pub(restricted)` reached stable in rustc 1.18. You can work around this on older compiler versions by running `cargo +nightly install racer`
