### ISSUE TITLE
Why racer can not complete print functions?

### ISSUE THREAD

**Issue by zjhmale** [racer-rust/racer#801]
Hi, I think the `println!` function is somewhere in the rust source, and my `RUST_SRC_PATH` variable is set up correctly I believe, so why can't racer complete it for me?

![image](https://user-images.githubusercontent.com/6234553/31264438-a2c990b0-aa9b-11e7-8bc5-faa4f0829cea.png)

Thanks in advance :)

**Comment by cideM** [comment]
I am a complete rust noob who hasn't even read past the first page of The Book yet, but `println!` appears to be a macro and macro support is still in its infancy, according to this [pull request](https://github.com/racer-rust/racer/pull/463)

**Comment by zjhmale** [comment]
@cideM Thanks :)
