### ISSUE TITLE
racer 2.0.11 does not complete anything

### ISSUE THREAD

**Issue by YaLTeR** [racer-rust/racer#806]
Updated *working* racer from 2.0.10 to 2.0.11. Now `racer complete std::` or any other complete request returns an empty response. A clean install of 2.0.11 on another PC also returns an empty response.

**Comment by golddranks** [comment]
It has to be because of the recent changes introduced in `RUST_SRC_PATHS` resolution.

I'm trying to diagnose the problem. Say do you have `RUST_SRC_PATHS` set? What is it set to?

Do you have `rustup` installed? What components does `rustup component list` mention as installed (or default)?

**Comment by golddranks** [comment]
Also: in what environment you use racer? (IDE? Plugins?)

**Comment by YaLTeR** [comment]
My `RUST_SRC_PATH` (not `PATHS`) is set to `/home/YaLTeR/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src` (on the other PC it's set to the stable source).

`rustup component list` shows (skipping not installed/default)
```
cargo-x86_64-unknown-linux-gnu (default)
rust-docs-x86_64-unknown-linux-gnu (default)
rust-src (installed)
cargo-x86_64-unknown-linux-gnu (default)
rust-docs-x86_64-unknown-linux-gnu (default)
rust-src (installed)
```
and for nightly:
```
cargo-x86_64-unknown-linux-gnu (default)
rls-preview-x86_64-unknown-linux-gnu (installed)
rust-analysis-x86_64-unknown-linux-gnu (installed)
rust-docs-x86_64-unknown-linux-gnu (default)
rust-src (installed)
rust-std-x86_64-unknown-linux-gnu (default)
rustc-x86_64-unknown-linux-gnu (default)
```

I usually use racer with RLS and [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) plugin.

**Comment by golddranks** [comment]
Oh shit, I think I found the bug. It was entirely a blunder of mine. I thought it would be fine, since the tests ran, but apparently there weren't any integration-like test cases that would have caught this! Writing a fix ATM.

**Comment by golddranks** [comment]
A fix is here: https://github.com/racer-rust/racer/pull/807
