### ISSUE TITLE
Racer doesn't find completions for `reqwest::Url::parse`

### ISSUE THREAD

**Issue by marmistrz** [racer-rust/racer#812]
I created the following snippet

```
extern crate reqwest;
use reqwest::Url;

fn main() {
    Url::
}
```
Then `racer complete-with-snippet 5 10 src/main.rs` returns nothing:
```
PREFIX 63,63,
END
```
If I extend the snippet to the semi-intended code

```
extern crate reqwest;
use reqwest::Url;

fn main() {
    Url::parse("");
}
```
everything compiles fine.

When autocompleting `use reqwest::`, the `Url` struct is not suggested either. RLS used from within VS Code suffers from the same problem since it uses Racer for completions.

Racer 2.0.12

**Comment by HeroicKatora** [comment]
This also seems to be the case in my current setup (and not only limited to reqwest but all completions for external creates):

> $ rustup show
> Default host: x86_64-unknown-linux-gnu
> 
> stable-x86_64-unknown-linux-gnu (default)
> rustc 1.22.1 (05e2e1c41 2017-11-22)

> $ racer --version
> racer 2.0.12

**Comment by kngwyu** [comment]
```request::Url``` is imported from ```url::Url``` crate.
It seems that Racer can't find definitions in "sub imported" crate like ```request:::Url``` if there's no "Cargo.lock" file.
I checked after "Cargo.lock" is generated, racer becomes to be able to complete ```request::Url```.
