### ISSUE TITLE
Racer fails to complete with a multibyte comment in a match statement 

### ISSUE THREAD

**Issue by kngwyu** [racer-rust/racer#816]
When a comment with multibyte chars is inserted where match expressions should be placed, racer fails to complete in the area between that comment and the end of the match statement.
See below.
```rust
fn main() {
    let a = 3;
    let long_name_variable = 0;
    let s = match a {
        1 => "cat",
        2 => "ls",
        // comment with multibyte chars, like ★
        _ => {
            let b = long_name_v..; // this fails
            "wc"
        }
    };
    let c = long_name_v..; // this succeeds
}
```
In this example,  racer fails to complete ```let b = long_name_variable```, but succeeds ```let c = long_name_variable```.
I'm using racer 2.0.12.

**Comment by TedDriggs** [comment]
Fixed in #819
