### ISSUE TITLE
Racer doesn't autocomplete unsafe functions

### ISSUE THREAD

**Issue by Starz0r** [racer-rust/racer#821]
Racer doesn't seem to catch unsafe functions for any crates, specifically the one I tested with was the winapi one. If you download a crate while writing the project, if you try to use any unsafe functions, it will not appear while typing (even though docs.rs says these functions exist). Structs appear within then namespace, showing that it can autocomplete the crate, but nothing else appears because all the functions related to the namespace all are unsafe. The only editor I have tested this with is Atom, and so far it is easily reproducible there.

Atom: 1.24.0-beta3
Rust: stable-x86_64-pc-windows-msvc
rustc 1.23.0 (766bd11c8 2018-01-01)
Racer: 2.0.12

**Comment by Starz0r** [comment]
@kngwyu In my tests, anything under winapi::um::shellapi::, but specifically, the function I tried to use was winapi::um::shellapi::SHELLEXECUTEINFOA

**Comment by kngwyu** [comment]
Racer  can't complete that function **not** because it's undafe,  but **it's declared in macro**.
See https://github.com/retep998/winapi-rs/blob/0.3/src/um/shellapi.rs#L309-325.
Completion of names declared in macro is not supported now(sorry).

**Comment by Starz0r** [comment]
@kngwyu Thanks for clarifying.

I'm going to close the issue then, if someone can label it afterwards, that would be nice.
