### ISSUE TITLE
Racer doesn't support types output by a macro

### ISSUE THREAD

**Issue by Lokathor** [racer-rust/racer#824]
There seems to be a few other issues with macros floating about, but this seems different enough to bring up. If not you can delete it.

Basically, If there's a macro that generates a struct (presumably an enum or union as well) then the type and it's fields won't be available for racer completion.

**Comment by kngwyu** [comment]
Thanks for opening an issue.
Now, racer don't expand macros at all, so completion of  any names declared in macros is unsupported.
Though I want to solve this issue, it doesn't seem to be so easy.

**Comment by Lokathor** [comment]
Can't you run racer on the results of `rustc --pretty=expanded`? One of the other issue threads said that it'd be "slower", but I'm wondering how much slower, and also if it could be available as a flag we could put and then have in the rls-vscode plugin somewhere. I'd probably take slightly laggy types over no types.

**Comment by kngwyu** [comment]
I think just calling ```syntax::noop_fold_mac``` is enough.
I'll try prototyping.

**Comment by TedDriggs** [comment]
@kngwyu is correct. @Lokathor we've looked at various approaches for macros, but they were all pretty ugly. I don't anticipate racer ever solving the macro question; that'll be something that comes from RLS.
