### ISSUE TITLE
Most completions aren't working

### ISSUE THREAD

**Issue by robsmith11** [racer-rust/racer#832]
I've followed the installation instructions in the README, but completions aren't working for many things like the Vec example screenshot.  It seems that completions work for most 3rd party crates that I install though as well as all module imports.

Any idea what's wrong or how to debug this?

```
$ rustc -vV
rustc 1.26.0-nightly (0ff9872b2 2018-02-28)
binary: rustc
commit-hash: 0ff9872b2280009f094af0df3dcdc542cc46a5fd
commit-date: 2018-02-28
host: x86_64-unknown-linux-gnu
release: 1.26.0-nightly
LLVM version: 6.0
```

```
$ echo $RUST_SRC_PATH
/home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src
$ ls $RUST_SRC_PATH
build_helper  jemalloc           liballoc_system       libcore         libpanic_unwind       librustc_lsan  libstd          libtest
Cargo.lock    liballoc           libbacktrace          liblibc         libprofiler_builtins  librustc_msan  libstd_unicode  libunwind
dlmalloc      liballoc_jemalloc  libcompiler_builtins  libpanic_abort  librustc_asan         librustc_tsan  libterm         rustc
```

```
$ racer complete std::io::B
MATCH BufRead,1363,10,/home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/mod.rs,Trait,pub trait BufRead: Read
MATCH Bytes,1984,11,/home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/mod.rs,Struct,pub struct Bytes<R>
MATCH BufReader,50,11,/home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/buffered.rs,Struct,pub struct BufReader<R>
MATCH BufWriter,378,11,/home/me/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/io/buffered.rs,Struct,pub struct BufWriter<W: Write>
```

**Comment by kngwyu** [comment]
Hmm...
It looks racer works.
Could you please try the following steps?
- save this snippet as `example.rs`
```rust
fn main() {
    let v = Vec::new();
    v.
}
```
- change working directory to where `example.rs` is and 
```bash
racer complete 3 6 example.rs
```

**Comment by robsmith11** [comment]
Ah in my Vec example I had used a macro and didn't use an explicit type, which I guess isn't supported.  Your example does indeed work.

But if I change it slightly like below, I don't get any completions:
```
fn main() {
    let v:f64 = 0.0;
    v.
}
````
```
$ racer complete 3 6 example.rs
PREFIX 39,39,
END
```

**Comment by kngwyu** [comment]
@robsmith11 
Oh, currently method completion for primitive type is not supported(#401).
Sorry for poor completion...

**Comment by robsmith11** [comment]
Ah ok.  A couple other things I tried using your example:
* `v.iter()` doesn't show up as a possible completion for `v.it`.  Shouldn't it?
* `v.into_iter().` doesn't produce any completions (but `v.into` does complete to `v.into_iter`).

**Comment by kngwyu** [comment]
@robsmith11 
I could reproduce both, but I think theyr'e bug and should be fixed.
For ``into_iter()``), it looks type inference based on associated types doesn't work correctly.
For `iter()`, sorry, I have any idea now and I'm going to check deeper.

Thanks for reporting!

**Comment by TedDriggs** [comment]
> For iter(), sorry, I have any idea now and I'm going to check deeper.

@kngwyu I believe this is because `iter` isn't declared in the same place as `Vec`. Racer finds the file with the struct and then looks there for traits and methods because it doesn't have a global index like `rustc` does. I went down the same road and couldn't think of a way to fix it without killing performance.

**Comment by kngwyu** [comment]
@TedDriggs 
Thanks.
So it seems to be difficult to fix now.
I will reopen this issue in the future.
