### ISSUE TITLE
Replace syntex with libsyntax or rustc-ap-syntax

### ISSUE THREAD

**Issue by topecongiro** [racer-rust/racer#836]
AFAIK `syntex` was deprecated more than a year ago, so `racer` may not recognize the latest syntax. Is it possible to replace `syntex` with `libsyntax` or `rustc-ap-syntax`?

**Comment by kngwyu** [comment]
I'm working on [my branch](https://github.com/kngwyu/racer-nightly/pull/1), though it's WIP and I have no plan to merge this branch into upstream.

**Comment by kngwyu** [comment]
[Nightly vesrion](https://github.com/kngwyu/racer-nightly) is now ready to use, though still there's a lot of TODO.

**Comment by kngwyu** [comment]
Closed via #854
