### ISSUE TITLE
Version 2.0.13 was not tagged as a release

### ISSUE THREAD

**Issue by faulesocke** [racer-rust/racer#842]
According to crates.io, version 2.0.13 of racer was released on 2018-03-20. However, this release was not tagged here on github and therefore it's hard to find the exact commit. Tagging releases is also quite important for several linux distros, as they will only accept to package released versions in their software repositories.

Therefore, please add a tag for version 2.0.13.

**Comment by kngwyu** [comment]
Closed since 2.0.14 was released
