### ISSUE TITLE
git dependencies aren't recognized if uppercase is used in url

### ISSUE THREAD

**Issue by warsus** [racer-rust/racer#846]
I just did some research to find out why completions for my cursive dependency from git did not work.
I declared it as following, but as it turns out the uppercase 'C' seems to break racer.

cursive = { git = "https://github.com/gyscos/Cursive.git"}

If i only use lowercase letters for the repository name it works.

cursive = { git = "https://github.com/gyscos/cursive.git"}

In the former case in find_git_src_dir the uppercase "Cursive" from the url, is compared (by starts_with) to the directory name of the checkout, which happens to be lowercase, so the whole directory gets skipped. 

A simple solution would obviously be to call to_lowercase at some point before.

**Comment by kngwyu** [comment]
Thanks, but I'm planning to apply https://github.com/kngwyu/racer-nightly/pull/3 to upstream and it will fix this kind of problem.

**Comment by kngwyu** [comment]
Closed via #855
