### ISSUE TITLE
racer pegs CPU for minutes when using the combine crate (w/repro)

### ISSUE THREAD

**Issue by mullr** [racer-rust/racer#872]
Whenever I use 'combine' parser combinator crate, racer consumes 100% cpu for minutes at a time when it tries to do a completion. 

A minimal repro (from the user side) is available here: https://github.com/mullr/racer-with-combine-repro

I don't know what about `combine` triggers this behavior, but running `RUST_LOG=racer=debug ./complete.sh 2>&1 | less` seems to indicate that combine's lib.rs is getting repeatedly parsed.

**Comment by kngwyu** [comment]
Thanks for reporting! 
I could reproduce, and I'm debugging now.
I think it's related to #844, but not sure.

**Comment by kngwyu** [comment]
OMG....
```rust
DEBUG 2018-06-16T05:08:27.141959186Z: racer::matchers: found a module inline: |pub mod combinator {
    #[doc(inline)]
    pub use parser::choice::*;
    #[doc(inline)]
    pub use parser::combinator::*;
    #[doc(inline)]
    pub use parser::error::*;
    #[doc(inline)]
    pub use parser::function::*;
    #[doc(inline)]
    pub use parser::item::*;
    #[doc(inline)]
    pub use parser::repeat::*;
    #[doc(inline)]
    pub use parser::sequence::*;
}|
```

So maybe #844 is very critical for performance and, yeah, we have to fix it as soon as possible.

**Comment by birkenfeld** [comment]
I'd propose, as a short-term additional mitigation, a configurable timeout after which Racer just returns with no matches.

**Comment by kngwyu** [comment]
@birkenfeld 
To set timeout sounds good idea.
I know there's some cases racer becomes very slow other than this(e.g. iterator chain), and it'll take much more time to fix them all, than set timeout.

But, for this problem, I'm considering another approach(to explain is a bit difficult... I open a PR soon).

**Comment by kngwyu** [comment]
I decided to close this via #875
