### ISSUE TITLE
Rust 2018 edition use statement with crate keyword not recognized

### ISSUE THREAD

**Issue by nrc** [racer-rust/racer#880]
Reported in https://github.com/nrc/rls-analysis/issues/144, but I'm pretty sure this is a Racer issue.

`use crate::point::Point;` gives "error: expected identifier, found keyword `crate`"

Perhaps we just need to use a later version of Racer in the RLS with a parser which can handle this?

**Comment by kngwyu** [comment]
> Perhaps we just need to use a later version of Racer in the RLS with a parser which can handle this?

No, we need to modify codes to handle `crate` keyword when parsing use statement.
But, honestly I don't understand [crate_in_paths](https://doc.rust-lang.org/nightly/unstable-book/language-features/crate-in-paths.html) enough...
Is `use crate::a` is same as `use  ::a`?

**Comment by kngwyu** [comment]
@nrc 
Thanks, it looks a big change!
I'm going to implement `use crate::~` support on this weekend.

**Comment by kngwyu** [comment]
Closed via #891
