### ISSUE TITLE
Racer not completing types from extern blocks.

### ISSUE THREAD

**Issue by sengirab** [racer-rust/racer#890]
Hi.

When defining functions in an extern block.
Importing the module in e.g main.rs doesn't autocomplete functions from within the extern blocks.

![screen shot 2018-07-15 at 1 08 38 pm](https://user-images.githubusercontent.com/15229540/42733343-40c2959c-8830-11e8-8c74-9de6894c8264.png)
![screen shot 2018-07-15 at 1 08 42 pm](https://user-images.githubusercontent.com/15229540/42733344-40d6b518-8830-11e8-9e98-d9683c0da008.png)
![screen shot 2018-07-15 at 1 08 47 pm](https://user-images.githubusercontent.com/15229540/42733345-40e9e250-8830-11e8-987f-7744147b2891.png)

- rust 1.27.0
- racer 2.0.14

**Comment by kngwyu** [comment]
Thanks.
It's also reported in #878 but has been neglected because of other bugs.

**Comment by kngwyu** [comment]
Closed via #895
