### ISSUE TITLE
error: expected expression, found `<eof>`

### ISSUE THREAD

**Issue by doxxx** [racer-rust/racer#897]
I'm having trouble with completions working very inconsistently for my Rust project in VSCode. I enabled rls and rls-analysis debug logging and eventually noticed this in the log output:

```
error: expected expression, found `<eof>`
 --> bogofile:1:32
  |
1 | pub struct Matrix44f(pub [[f64;
  |                                ^

error: expected one of `;`, `<`, `break`, `continue`, `false`, `for`, `if`, `loop`, `match`, `move`, `return`, `true`, `unsafe`, `where`, or `while`, found `<eof>`
 --> bogofile:1:32
  |
1 | pub struct Matrix44f(pub [[f64;
  |                                ^

error: internal compiler error: Error constructed but not emitted

thread 'request-worker-0' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_errors-0.52.0\src\diagnostic_builder.rs:192:13
stack backtrace:
   0: <std::sys::windows::args::Args as core::ops::drop::Drop>::drop
   1: std::error::<impl core::convert::From<alloc::borrow::Cow<'b, str>> for alloc::boxed::Box<(dyn std::error::Error + core::marker::Sync + core::marker::Send + 'a)>>::from
   2: std::panicking::take_hook
   3: std::panicking::take_hook
   4: <rustc::ty::SymbolName as core::fmt::Debug>::fmt
   5: std::panicking::rust_panic_with_hook
   6: git_reference_name
   7: git_reference_name
   8: git_merge_driver_source_file_options
   9: git_merge_driver_source_file_options
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: _rust_maybe_catch_panic
  15: <unknown>
  16: <unknown>
  17: _rust_maybe_catch_panic
  18: <unknown>
  19: git_merge_driver_source_file_options
  20: git_merge_driver_source_file_options
  21: git_merge_driver_source_file_options
  22: _rust_maybe_catch_panic
  23: git_merge_driver_source_file_options
  24: std::sys::windows::thread::Thread::new
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
query stack during panic:
end of query stack
```

EDIT: Was able to reproduce and get backtrace.

The file in which this struct is defined is not incomplete, so I don't know why it's complaining about EOF. The full definition of that type is:

```rust
#[derive(Debug, Clone, Copy)]
pub struct Matrix44f(pub [[f64; 4]; 4]);
```

My suspicion is that there's a parser somewhere getting confused.

The repo containing this source code can be found here: https://github.com/doxxx/raytracer. The file is `src/matrix.rs`.

RLS version 0.129.0-nightly (2b57851 2018-07-14)

**Comment by doxxx** [comment]
Possibly related to this, when I type a '.' after a local variable name, I immediately get this in the log:

```
error: internal compiler error: Error constructed but not emitted

thread 'request-worker-3' panicked at 'explicit panic', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\syntex_errors-0.52.0\src\diagnostic_builder.rs:192:13
stack backtrace:
query stack during panic:
end of query stack
```

**Comment by doxxx** [comment]
The above error seems to specifically occur when getting completions for a variable of type `Direction` (defined in `src/direction.rs`).

**Comment by kngwyu** [comment]
Thanks, it looks really terrible bug.

**Comment by kngwyu** [comment]
Now I succeeded to emit these errors, but I found they're not related to what completions we get.
@doxxx 
Could you please point out what ident/path/etc.. you can't get as completion candidates?
I'm going to try to work in your raytracer crate too, but your own feedback is more important.

**Comment by kngwyu** [comment]
One more:
> Possibly related to this, when I type a '.' after a local variable name, I immediately get this in the log:

This looks not related to racer

**Comment by doxxx** [comment]
> Could you please point out what ident/path/etc you can't get as completion candidates?

`src/system.rs` -> `Camera::new` function. I cannot get completions for any of the local variables or the `f64` parameters. I do get completions for the `Point` parameters.

I do get completions for the local variables if I type the first letter of the method after the dot. e.g. `up.n` provides completions for `ne`, `neg` (twice), and `normalize`.

**Comment by kngwyu** [comment]
Thanks!

> I do not get completions for methods on any of the local variables

For a local variable `xaxis` racer can get methods.
![screenshot from 2018-07-21 17-11-38](https://user-images.githubusercontent.com/16046705/43033708-482d7206-8d09-11e8-92f9-4859c6694463.png)
But, for `zaxis` and `yaxis`, racer fails to infer types of `-` operation.

>  or the f64 parameters

It's not yet supported(#401), sorry.

So I decided to close this issue in favour of #401 and I'll try to modify it.
Thanks for detailed explanation!

**Comment by doxxx** [comment]
Thanks for looking into it!
