### ISSUE TITLE
Autocomplete after `use std::`

### ISSUE THREAD

**Issue by ricvelozo** [racer-rust/racer#912]
I don't know if the problem is in Racer or RLS (or even in ide-rust), but I'd like if the suggestions list appear on `::`, and no to wait I type a letter, i.e.:

```rust
// currently:
use std::io::R
             ^--- shows suggetions list

// as I'd like
use std::io::
            ^--- shows suggetions list
```

**Comment by kngwyu** [comment]
Thanks for reporting!
But, I think it's not a racer's problem(e.g. in emacs client
![image](https://user-images.githubusercontent.com/16046705/43362447-49705724-9325-11e8-86b9-b5fc9932a1a1.png)
).

@ricvelozo 
What client do you use?
RLS and ide-rust?

**Comment by kngwyu** [comment]
Ah you mean you want to get `:BufRead :BufReader :BufWriter...` after typing `use std::io:`?
I misunderstood, sorry.

**Comment by ricvelozo** [comment]
More like to get `BufRead` after typing `use std::io::`.

**Comment by kngwyu** [comment]
I see.
I'm going to check it in Atom.

**Comment by kngwyu** [comment]
I can reproduce in [atom-ide-rust](https://github.com/rust-lang-nursery/atom-ide-rust) but can't reproduce in [rls-vscode](https://github.com/rust-lang-nursery/rls-vscode).
So it seems to be a problem of ide-rust.
