### ISSUE TITLE
Is it possible to shell out to `cargo metadata` rather than have cargo as a dep

### ISSUE THREAD

**Issue by nrc** [racer-rust/racer#914]
Coordinating the cargo version between racer, Cargo, and the RLS is a bit of a pain.

**Comment by kngwyu** [comment]
I think we can do so when https://github.com/rust-lang-nursery/rls/pull/965 is merged.

**Comment by phansch** [comment]
https://github.com/rust-lang-nursery/rls/pull/981 (a followup of https://github.com/rust-lang-nursery/rls/pull/965) has been merged

**Comment by kngwyu** [comment]
Closed via #930
