### ISSUE TITLE
find-definition requires `extern crate` in 2018 edition

### ISSUE THREAD

**Issue by tarka** [racer-rust/racer#916]
`extern crate` is no longer required in the 2018 edition preview. However, trying `find-definition 3 25` on the following code fails. However if add `extern crate actix_web;` it works.

    #![feature(rust_2018_preview)]

    use actix_web::{server, App, HttpRequest};

    fn index(_req: &HttpRequest) -> &'static str {
        "Hello world!"
    }

    fn main() {
       server::new(|| App::new().resource("/", |r| r.f(index)))
            .bind("127.0.0.1:8088")
            .unwrap()
            .run();
    }

(This is built from master 22033f9, using emacs-racer, but confirmed on the commandline.)

**Comment by kngwyu** [comment]
Thanks!
It's just not implemented yet :sweat:

**Comment by kngwyu** [comment]
By #930 racer know current project's edition.
Next step is to know 'where the current crate is'.

**Comment by tav** [comment]
Is anyone planning on working on this by any chance?

**Comment by kngwyu** [comment]
I'm worrying about the overhead of calling `cargo metadata` just to know what the edition is.
But, anyway, I'm going to include this in 2.2 release and any contribution is welcome.

**Comment by kngwyu** [comment]
Closed via #987
