### ISSUE TITLE
Find definition in use statement can jump into closure arg

### ISSUE THREAD

**Issue by kngwyu** [racer-rust/racer#926]
Awesome bug (⦿＿⦿)
```rust
use reqwest;
fn f() {
    let a = Some(5).map(|reqwest| {});
}
```
When we use `definition` on `use req~`, it returns  a closure arg below.
It's terrible :fearful:

**Comment by letmutx** [comment]
Hi! Can I pick this? My idea to solve this is to not consider matches from closures if the search string is not in the closure's scope. From a little debugging I found that the `extern crate reqwest` also matches but only the first result is picked because this context is an exact match.

**Comment by kngwyu** [comment]
> to not consider matches from closures if the search string is not in the closure's scope

Yes, we should.

**Comment by letmutx** [comment]
Okay, I'll try to find the root cause. As I understand, _children_scopes shouldn't (is that the correct word?)  shouldn't be even considered to search matches from. Is that correct?

**Comment by kngwyu** [comment]
> Is that correct?

Yes. 
In [resolve_name](https://github.com/racer-rust/racer/blob/3be80e8646f5880c57a17fc3fa9f6cd84676a796/src/racer/nameres.rs#L1414), first [search_local_scopes](https://github.com/racer-rust/racer/blob/3be80e8646f5880c57a17fc3fa9f6cd84676a796/src/racer/nameres.rs#L1258) is called, and then [search_crate_root](https://github.com/racer-rust/racer/blob/3be80e8646f5880c57a17fc3fa9f6cd84676a796/src/racer/nameres.rs#L850) is called.
And I think there's a bug in search_local_scopes.

**Comment by letmutx** [comment]
@kngwyu Why is the whole scope searched if `pos == BytePos::ZERO` here?
https://github.com/racer-rust/racer/blob/master/src/racer/nameres.rs#L1277

**Comment by kngwyu** [comment]
@letmutx 
It's just a short-cut.
If `pos != 0` we search scopes recursively.
E.g.
```
mod mo {
    fn mod func() {}
    fn f() {
        // headers
        let a = 5;
        let b = 4;
        let c = ~ // completion point
        // names
        fn inner_func1() {}
        struct 
    }
}
```
If we throw a completion query at `let c = ~`,
1. search for functions/structs/... in `fn f()`
2. search local variable above `let c=`, in `fn f()` (by `search_scope_headers`)
3. search for functions/structs/... in `mod m`
4. search local variable above `let c=`, in `mod` (this is inefficient and we should fix this)

But if `pos == 0` we don't have to call `search_scope_headers`, so just call `search_scope`.

**Comment by letmutx** [comment]
Sorry for the confusion, here is the `point` I am referring to. https://github.com/racer-rust/racer/blob/master/src/racer/nameres.rs#L952 I am trying to use it like this: https://github.com/racer-rust/racer/pull/969/files#diff-9b67b9113cab3ef74c5b678891f0bb95R1169 but when the resolve_path

**Comment by kngwyu** [comment]
Sorry for delay.
1. `point` is equal to `start`
We have no completion point in this scope. We have to search the whole scope.
2. `point` is not equal to `start`
It's a completion point. We have to search local variables.
And, `start` is a offset to `src`. It's used for get correct position of names.

**Comment by letmutx** [comment]
@kngwyu I made yet another attempt at fixing this. The call to `search_closure_args` in `search_scope` ([link](https://github.com/racer-rust/racer/blob/98b761cce6ddc57dd51c147d8f473cb4c4d8fd55/src/racer/nameres.rs#L1129)) was causing this issue. It just tries to find a closure by finding a pair of `|` and tries to match the args without checking if the point is inside the closure. In the first call to `search_scope` the scope to search is the whole file; closure inside `main` is found and its args are matched against the search str. I couldn't find any other bug in search scopes. Please let me know if you have anything else in mind.

**Comment by kngwyu** [comment]
Good catch, thanks!
