### ISSUE TITLE
Correctly handle multiple-use

### ISSUE THREAD

**Issue by porglezomp** [racer-rust/racer#96]
It would be nice if line like `std::io::{` would complete the same as `std::io::`
It would be even nicer if, for instance `use std::rc::{Rc,` would recommend everything that `std::rc::` recommends, except it would omit `Rc` since it's already being used.

**Comment by TedDriggs** [comment]
Technically, the following code is valid:

```rust
use std::fmt::{Formatter, Formatter as Fmtr};
```

I have no idea _why_ someone would do this, but since it's allowed I'm reluctant to have rust hide things that have already been imported in the current `use` statement.

**Comment by porglezomp** [comment]
I was a little surprised to get this notification, but as far as I can tell the main issue here was resolved a while ago thanks to @yodalee, so I'm happy to have this issue closed.
